Repository team-xquare/xquare-iOS, pull requests merged in 2022-06, with the labels that each got.

#42 🔀 :: (#39) change application interface
  Application/Sources/AppDelegate.swift
  Application/Sources/Application/XQUAREApp.swift
  Application/Sources/SceneDelegate.swift
Labels: 프로젝트 설정

#43 🔀 (#40) add rx moya to auth service
  Services/AuthService/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
Labels: 버그

#44 🔀 :: (#41) Tuist Dynamic Framework target version to 15.0
  Tuist/ProjectDescriptionHelpers/Project Frame/Project+DynamicFramework.swift
Labels: 버그, 프로젝트 설정

#45 🔀 :: (#37) DI
  Application/Sources/Application/XQUAREApp.swift
  Services/AuthService/Sources/DI/AuthServiceAssembly.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
Labels: 기능 추가, 프로젝트 설정

#46 🔀 :: (#34) rest api module
  Modules/RestApiModule/Sources/RestApiRemoteDataSource.swift
  Modules/RestApiModule/Sources/XquareAPI.swift
Labels: 기능 추가

#48 🔀 :: (#38) api base url 수정
  Services/AuthService/Sources/Data/Remote/API/AuthAPI.swift
Labels: chore

#55 🔀 :: (#27) CI
  .github/workflows/CI.yml
  Makefile
  Tuist/ProjectDescriptionHelpers/SwiftLintScripts.swift
Labels: 프로젝트 설정

#58 🔀 :: (#53) test rx offline cache module
  Modules/KeychainModule/Tests/.gitkeep
  Modules/RxOfflineCacheModule/Sources/OfflineCacheUtil.swift
  Modules/RxOfflineCacheModule/Tests/OfflineCacheUtilSpec.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project Frame/Project+DynamicFramework.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
Labels: 리팩토링, 테스트 추가

#60 🔀 :: (#59) Remove RealmModule
  Modules/RealmModule/Project.swift
  Modules/RealmModule/Sources/.gitkeep
  Modules/RealmModule/Tests/.gitkeep
  Services/MealDataService/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Modules.swift
Labels: 프로젝트 설정

#62 🔀 :: (#61) SQLiteModule Setting
  Modules/SQLiteModule/Project.swift
  Modules/SQLiteModule/Sources/.gitkeep
  Modules/SQLiteModule/Sources/SQLiteTask.swift
  Modules/SQLiteModule/Tests/SQLiteTaskSpec.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Modules.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
Labels: 프로젝트 설정

#65 🔀 :: SQLiteTask
  Modules/SQLiteModule/Sources/SQLiteError.swift
  Modules/SQLiteModule/Sources/SQLiteTask.swift
  Modules/SQLiteModule/Sources/xquare.sqlite
Labels: 기능 추가
