Repository team-xquare/xquare-iOS, pull requests merged in 2022-08, with the labels that each got.

#161 🔀 :: (#139) HomeView MealDataService 설정해주기
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Home/HomeViewModel.swift
  Application/Sources/Scene/Home/Meal/MealListCell.swift
  Application/Sources/Scene/Home/Meal/MealMenuView.swift
  Services/MealDataService/Sources/Domain/Entity/MealMenuEntity.swift
Labels: 기능 추가

#170 🔀 :: (#169) SD-Version Update
  Tuist/Dependencies.swift
Labels: 프로젝트 설정

#173 🔀 :: (#155) develop XWebKit
  Modules/XWebKit/Project.swift
  Modules/XWebKit/Sources/ComposedWebView/ComposedWebView.swift
  Modules/XWebKit/Sources/ComposedWebView/WebViewCoordinator.swift
  Modules/XWebKit/Sources/XWebKitProgressViewStyle.swift
  Modules/XWebKit/Sources/XWebKitState.swift
  Modules/XWebKit/Sources/XWebKitView.swift
Labels: 기능 추가

#171 🔀 :: (#105) LoginView Publishing
  Application/Sources/Scene/FindId/FindIdView.swift
  Application/Sources/Scene/FindPassword/FindPasswordView.swift
  Application/Sources/Scene/Login/FindButtonView/FindButtonView.swift
  Application/Sources/Scene/Login/LoginView.swift
  Application/Sources/Scene/Login/LoginViewModel.swift
Labels: 기능 추가

#172 🔀 :: (#106) SignUp Scene 퍼블리싱
  Application/Sources/Scene/SignUp/SignUpView.swift
  Application/Sources/Scene/SignUp/SignUpViewModel.swift
Labels: 기능 추가

#177 🔀 :: (#176) XNavigationLink 개발
  Modules/XNavigationLink/Project.swift
  Modules/XNavigationLink/Sources/XNavigationLinkWithoutTabbar.swift
  Modules/XNavigationLink/Tests/.gitkeep
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Modules.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
Labels: 기능 추가

#178 🔀 :: (#175) XWebKit navigation시 tabbar 숨기기
  Modules/XWebKit/Project.swift
  Modules/XWebKit/Sources/XWebKitView.swift
Labels: chore

#180 🔀 :: (#179) 탭바 버그 수정
  Modules/XNavigationLink/Sources/OnChangePresentationMode.swift
  Modules/XNavigationLink/Sources/XNavigationLinkWithoutTabbar.swift
  Modules/XWebKit/Sources/XWebKitView.swift
Labels: 버그

#183 🔀 :: (#181, #182) 코드 정리 및 RootPresentationMode 추가
  Modules/XNavigation/Project.swift
  Modules/XNavigation/Sources/RootPresentationMode.swift
  Modules/XNavigation/Sources/Util/HideTabBarWhenNavigate.swift
  Modules/XNavigation/Sources/Util/OnChangePresentationMode.swift
  Modules/XNavigation/Sources/XNavigationLink.swift
  Modules/XNavigation/Tests/.gitkeep
  Modules/XNavigationLink/Sources/XNavigationLinkWithoutTabbar.swift
  Modules/XWebKit/Project.swift
  Modules/XWebKit/Sources/XWebKitView.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Modules.swift
Labels: 리팩토링, 기능 추가

#186 🔀 :: (#184) 필요없는 코드 제거 및 숨겨진 탭바 크기 무시
  Modules/XNavigation/Sources/Util/HideTabBarWhenNavigate.swift
  Modules/XNavigation/Sources/Util/OnChangePresentationMode.swift
Labels: 리팩토링, chore

#191 🔀 :: (#190) Request init 접근제한 변경
  Services/AuthService/Sources/Domain/Entity/SigninEntity.swift
  Services/AuthService/Sources/Domain/Entity/SignupEntity.swift
Labels: chore

#194 🔀 :: (#193) SD-Version-Update
  Tuist/Dependencies.swift
Labels: 프로젝트 설정

#199 🔀 :: (#198) SD 업데이트
  Tuist/Dependencies.swift
Labels: 프로젝트 설정

#201 🔀 (#192) 보이지 않는 급식 버그 해결
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Home/HomeViewModel.swift
  Application/Sources/Scene/Home/Meal/MealListCell.swift
  Application/Sources/Scene/Home/Meal/MealMenuView.swift
  Application/Sources/Scene/Home/Profile/ProfileView.swift
Labels: 버그, 리팩토링

#202 🔀 (#187) FCM setting
  .tuist-version
  Application/Project.swift
  Application/Resources/GoogleService-Info.plist
  Application/Sources/Application/AppDelegate.swift
  Application/Sources/Application/XQUAREApp.swift
  Application/SupportingFiles/Info.plist
  Application/SupportingFiles/XQUARE-iOS.entitlements
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project Frame/Project+Excutable.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
Labels: 기능 추가, 프로젝트 설정

#197 🔀 :: (#196 ) XNaviagation 이름 변경및 전체 개편
  Application/Project.swift
  Modules/XNavigation/Sources/RootPresentationMode.swift
  Modules/XNavigation/Sources/Util/HideTabBarWhenNavigate.swift
  Modules/XNavigation/Sources/XNavigationLink.swift
  Modules/XNavigationAndTab/Project.swift
  Modules/XNavigationAndTab/Sources/BackToMainView.swift
  Modules/XNavigationAndTab/Sources/Entity/TabInformation.swift
  Modules/XNavigationAndTab/Sources/Entity/Toolbar.swift
  Modules/XNavigationAndTab/Sources/Environment/TabBarSelection.swift
  Modules/XNavigationAndTab/Sources/Util/ViewToAnyView.swift
  Modules/XNavigationAndTab/Sources/Util/XNavigationAndTabUtil.swift
  Modules/XNavigationAndTab/Sources/XNavigationAndTabContent.swift
  Modules/XNavigationAndTab/Sources/XNavigationAndTabView.swift
  Modules/XNavigationAndTab/Tests/.gitkeep
  Modules/XWebKit/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Modules.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
Labels: 리팩토링, 기능 추가

#204 🔀 :: (#189) SignUpViewModel
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/SignUp/SignUpView.swift
  Application/Sources/Scene/SignUp/SignUpViewModel.swift
  Services/AuthService/Sources/Data/Remote/API/AuthAPI.swift
  Services/AuthService/Sources/Data/Remote/Request/SignupRequest.swift
  Services/AuthService/Sources/Domain/Entity/SignupEntity.swift
  Services/AuthService/Sources/Domain/Error/AuthServiceError.swift
Labels: 기능 추가

#207 🔀 :: (#206) XNavigationAndTab 업데이트 대응
  Application/Sources/Scene/Application/ApplicationView.swift
  Application/Sources/Scene/Entire/EntireView.swift
  Application/Sources/Scene/Feed/FeedView.swift
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Main/MainView.swift
  Application/Sources/Scene/Schedule/ScheduleView.swift
  Modules/XNavigationAndTab/Sources/XNavigationAndTabContent.swift
  Modules/XWebKit/Sources/XWebKitState.swift
  Modules/XWebKit/Sources/XWebKitView.swift
Labels: 리팩토링

#209 🔀 :: (#188) LoginViewModel 연동하기
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/Login/LoginView.swift
  Application/Sources/Scene/Login/LoginViewModel.swift
  Application/Sources/Scene/SignUp/SignUpView.swift
  Services/AuthService/Sources/Data/Remote/Response/SigninAndRefreshTokenResponse.swift
Labels: 기능 추가
