Repository team-xquare/xquare-iOS, pull requests merged in 2022-09, with the labels that each got.

#211 🔀 :: (#210) [임시] 서버 교체
  Modules/RestApiModule/Sources/XquareAPI.swift
  Services/AuthService/Sources/Data/Remote/API/AuthAPI.swift
Labels: chore

#213 🔀 :: (#128) 온보딩화면
  Application/Resources/Assets.xcassets/Image/Onboarding/Contents.json
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-DMS.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-DMS.imageset/Onboarding-DMS1x.png
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-DMS.imageset/Onboarding-DMS2x.png
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-DMS.imageset/Onboarding-DMS3x.png
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Application/XQUAREApp.swift
  Application/Sources/ResoucesCode/Image.swift
  Application/Sources/Scene/LaunchScreen/LaunchScreenView.swift
  Application/Sources/Scene/LaunchScreen/LaunchScreenViewModel.swift
  Application/Sources/Scene/Login/LoginView.swift
  Application/Sources/Scene/Main/MainView.swift
  Application/Sources/Scene/Onboarding/OnboardingImageViewer.swift
  Application/Sources/Scene/Onboarding/OnboardingView.swift
  Application/Sources/Scene/SignUp/SignUpView.swift
Labels: 기능 추가

#214 🔀 :: (#212) 약관 들들 Signup페이지에 추가
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/Onboarding/OnboardingView.swift
  Application/Sources/Scene/Signup/SignupView.swift
  Application/Sources/Scene/Signup/SignupViewModel.swift
  Application/Sources/Scene/Signup/TermsCaptionView.swift
Labels: 리팩토링, 기능 추가

#218 🔀 :: (#217) send device token when login
  Application/Sources/Scene/Login/LoginViewModel.swift
  Application/SupportingFiles/Info.plist
Labels: chore, 기능 추가

#219 🔀 :: (#216) 회원가입 에러 해결
  Application/Sources/Scene/Signup/SignupViewModel.swift
  Services/AuthService/Sources/Data/Remote/Request/SignupRequest.swift
  Services/AuthService/Sources/Domain/Entity/SignupEntity.swift
Labels: 버그

#222 🔀 :: (#221) 보라맛 UI 버그 해결
  Modules/XWebKit/Sources/XWebKitProgressViewStyle.swift
Labels: 버그

#223 🔀 :: (#200) SQLite 오류 해결
  Application/Sources/Scene/Home/Meal/MealMenuView.swift
  Services/MealDataService/Sources/Data/Local/DataSource/LocalDataSource.swift
  Services/MealDataService/Sources/Data/Local/DataSource/LocalDataSourceImpl.swift
  Services/MealDataService/Sources/Data/Local/Entity/MealMenu.swift
  Services/MealDataService/Sources/Data/Local/MealDataServiceSQLiteTask.swift
  Services/MealDataService/Sources/Data/Remote/Response/MealMenuPerDayResponse.swift
  Services/MealDataService/Sources/Data/Repository/MealRepositoryImpl.swift
  Services/MealDataService/Sources/Domain/Entity/MealMenuEntity.swift
Labels: chore, 기능 추가

#228 🔀 :: (#174) send token to webview
  Modules/XWebKit/Sources/ComposedWebView/ComposedWebView.swift
  Modules/XWebKit/Sources/ComposedWebView/WebViewCoordinator.swift
  Modules/XWebKit/Sources/XWebKitState.swift
  Modules/XWebKit/Sources/XWebKitView.swift
Labels: 기능 추가

#229 🔀 :: (#226) FetchAccessTokenUseCase
  Services/AuthService/Sources/DI/AuthServiceDependency.swift
  Services/AuthService/Sources/Data/Repository/AuthRepositoryImpl.swift
  Services/AuthService/Sources/Domain/Repository/AuthRepository.swift
  Services/AuthService/Sources/Domain/UseCase/FetchAccessTokenUseCase.swift
Labels: 기능 추가

#230 🔀 :: (#227) 신청 페이지 webview 연동
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/Application/ApplicationView.swift
  Application/Sources/Scene/Application/ApplicationViewModel.swift
Labels: 기능 추가

#237 🔀 :: (#236) add date to string method with string format
  Modules/DateUtilModule/Sources/DateFormat.swift
  Modules/DateUtilModule/Sources/DateToString.swift
  Services/MealDataService/Sources/Data/Local/MealDataServiceSQLiteTask.swift
  Services/MealDataService/Sources/Data/Repository/MealRepositoryImpl.swift
Labels: 기능 추가

#235 🔀 :: (#234) disable OS_ACTIVITY_MODE
  Tuist/ProjectDescriptionHelpers/Project Frame/Project+Excutable.swift
Labels: 프로젝트 설정

#241 🔀 :: (#239) Date Local 한국으로 지정하기
  Modules/DateUtilModule/Sources/DateToString.swift
Labels: chore

#242 🔀 :: (#240) MealMenuPerDayEntity 이니셜라이저 퍼블릭으로 변경
  Services/MealDataService/Sources/Domain/Entity/MealMenuPerDayEntity.swift
Labels: chore

#243 🔀 :: (#238) MealDetail Scene UI 퍼블리싱
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Home/Meal/MealMenuView.swift
  Application/Sources/Scene/MealDetail/Cell/MealDetailCell.swift
  Application/Sources/Scene/MealDetail/Cell/MealMenuPerMealTimeView.swift
  Application/Sources/Scene/MealDetail/MealDetailView.swift
  Application/Sources/Scene/MealDetail/MealDetailViewModel.swift
  Services/MealDataService/Sources/Domain/Enum/MealTime.swift
Labels: 기능 추가

#248 🔀 :: (#247) xcode14 rx web kit error
  Modules/XWebKit/Project.swift
  Modules/XWebKit/Sources/ComposedWebView/ComposedWebView.swift
  Modules/XWebKit/Sources/RxWebKit/EstimatedProgress.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
Labels: 버그

#246 🔀 :: (#245) remove Introspect on SPM
  Tuist/Dependencies.swift
Labels: chore

#250 🔀 :: (#249) xcode14 issues about swiftlint scripts
  .tuist-version
  Tuist/ProjectDescriptionHelpers/SwiftLintScripts.swift
Labels: 버그, 프로젝트 설정

#254 🔀 :: (#251) 앱 분기처리
  Application/Resources/Firebase/GoogleService-Dev-Info.plist
  Application/Resources/Firebase/GoogleService-Prod-Info.plist
  Application/Resources/Firebase/GoogleService-Stage-Info.plist
  Application/SupportingFiles/Info.plist
  Configurations/develop.xcconfig
  Configurations/product.xcconfig
  Configurations/stage.xcconfig
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project Frame/Project+DynamicFramework.swift
  Tuist/ProjectDescriptionHelpers/Project Frame/Project+Excutable.swift
  Tuist/ProjectDescriptionHelpers/Scripts/GoogleServiceInfoPlistScripts.swift
  Tuist/ProjectDescriptionHelpers/Scripts/SwiftLintScripts.swift
Labels: 프로젝트 설정

#255 🔀 :: (#253) XEnvironment 모듈 개발 및 적용
  Modules/RestApiModule/Project.swift
  Modules/RestApiModule/Sources/XquareAPI.swift
  Modules/XEnvironment/Project.swift
  Modules/XEnvironment/Sources/XEnvironment.swift
  Modules/XEnvironment/SupportingFiles/Info.plist
  Modules/XEnvironment/Tests/.gitkeep
  Services/AuthService/Project.swift
  Services/AuthService/Sources/Data/Remote/API/AuthAPI.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Modules.swift
Labels: 기능 추가

#259 🔀 :: (#258) RemoveStaticFrameworksScripts
  Tuist/ProjectDescriptionHelpers/Project Frame/Project+DynamicFramework.swift
  Tuist/ProjectDescriptionHelpers/RemoveStaticFrameworksScripts.swift
Labels: 프로젝트 설정

#264 🔀 :: (#263) MealMenu kcal오류 해결
  Services/MealDataService/Sources/Data/Local/Entity/MealMenu.swift
  Services/MealDataService/Sources/Data/Local/MealDataServiceSQLiteTask.swift
  Services/MealDataService/Sources/Data/Repository/MealRepositoryImpl.swift
Labels: 버그

#267 🔀 :: (#266) XDateUtil 코드 리펙토링
  Modules/DateUtilModule/Sources/StringToDate.swift
  Modules/XDateUtil/Project.swift
  Modules/XDateUtil/Sources/DateFormat.swift
  Modules/XDateUtil/Sources/DateToString.swift
  Modules/XDateUtil/Sources/StringToDate.swift
  Modules/XDateUtil/Sources/XDateFormatter.swift
  Modules/XDateUtil/Tests/DateToStringSpec.swift
  Modules/XDateUtil/Tests/StringToDateSpec.swift
  Services/AuthService/Project.swift
  Services/AuthService/Sources/Data/Local/DataSource/LoaclTokenDataSourceImpl.swift
  Services/MealDataService/Project.swift
  Services/MealDataService/Sources/Data/Local/MealDataServiceSQLiteTask.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Modules.swift
Labels: 리팩토링, 프로젝트 설정

#233 🔀 :: (#224) 유저 서비스를 작성합니다.
  Services/UserService/Project.swift
  Services/UserService/Sources/.gitkeep
  Services/UserService/Sources/DI/UserServiceDependency.swift
  Services/UserService/Sources/Data/Remote/API/UserAPI.swift
  Services/UserService/Sources/Data/Remote/DataSource/RemotaUserDataSource.swift
  Services/UserService/Sources/Data/Remote/DataSource/RemoteUserDataSourceImpl.swift
  Services/UserService/Sources/Data/Remote/Repository/UserRepositoryImpl.swift
  Services/UserService/Sources/Data/Remote/Response/ClassUserListResponse.swift
  Services/UserService/Sources/Data/Remote/Response/ClassUserResponse.swift
  Services/UserService/Sources/Data/Remote/Response/FCMTokenResponse.swift
  Services/UserService/Sources/Data/Remote/Response/UserIdsResponse.swift
  Services/UserService/Sources/Data/Remote/Response/UserPointResponse.swift
  Services/UserService/Sources/Data/Remote/Response/UserResponse.swift
  Services/UserService/Sources/Domain/Entity/ClassUserEntity.swift
  Services/UserService/Sources/Domain/Entity/FCMTokensEntity.swift
  Services/UserService/Sources/Domain/Entity/UserEntity.swift
  Services/UserService/Sources/Domain/Entity/UserIdsEntity.swift
  Services/UserService/Sources/Domain/Entity/UserPointEntity.swift
  Services/UserService/Sources/Domain/Error/UserServiceError.swift
  Services/UserService/Sources/Domain/Repository/UserRepository.swift
  Services/UserService/Sources/Domain/UseCase/FetchExcludedUserListUseCase.swift
  Services/UserService/Sources/Domain/UseCase/FetchFCMTokenUseCase.swift
  Services/UserService/Sources/Domain/UseCase/FetchUserInformationByNameUseCase.swift
  Services/UserService/Sources/Domain/UseCase/FetchUserInformtaionByIdUseCase.swift
  Services/UserService/Sources/Domain/UseCase/FetchUserListByClassUseCase.swift
  Services/UserService/Sources/Domain/UseCase/FetchUserPointUseCase.swift
  Services/UserService/Tests/.gitkeep
  Tuist/ProjectDescriptionHelpers/TargetDependency/Services.swift
Labels: 기능 추가

#271 🔀 :: (#265) XNagivationAndTab 전체 개편
  Application/Sources/Application/XQUAREApp.swift
  Application/Sources/Scene/Application/ApplicationView.swift
  Application/Sources/Scene/Entire/EntireView.swift
  Application/Sources/Scene/Feed/FeedView.swift
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Main/MainView.swift
  Application/Sources/Scene/Schedule/ScheduleView.swift
  Modules/XNavigationAndTab/Project.swift
  Modules/XNavigationAndTab/Sources/BackToMainView.swift
  Modules/XNavigationAndTab/Sources/Entity/TabInformation.swift
  Modules/XNavigationAndTab/Sources/Entity/Toolbar.swift
  Modules/XNavigationAndTab/Sources/XNavigationAndTabContent.swift
  Modules/XNavigationAndTab/Sources/XNavigationAndTabView.swift
Labels: 리팩토링, chore

#274 🔀 :: (#273) 필요없는 것들들 삭제
  Application/Sources/Presentation/.gitkeep
  Modules/KeychainModule/Sources/.gitkeep
  Modules/RestApiModule/Sources/.gitkeep
  Modules/XNavigationAndTab/Sources/XNavigationAndTabView.swift
  Modules/XWebKit/Sources/.gitkeep
  Services/MealDataService/Sources/.gitkeep
  Services/UserService/Sources/.gitkeep
Labels: 리팩토링, chore

#276 🔀 :: (#275) 아이콘 세팅1
  .gitignore
  Application/Resources/Assets.xcassets/Image/Icon/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/Setting.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/Setting.imageset/설정.png
  Application/Resources/Assets.xcassets/Image/Icon/Setting.imageset/설정2x.png
  Application/Resources/Assets.xcassets/Image/Icon/Setting.imageset/설정3x.png
  Application/Resources/Assets.xcassets/Image/Icon/ViewMore.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/ViewMore.imageset/오른쪽 더보기.png
  Application/Resources/Assets.xcassets/Image/Icon/ViewMore.imageset/오른쪽 더보기2x.png
  Application/Resources/Assets.xcassets/Image/Icon/ViewMore.imageset/오른쪽 더보기3x.png
  Application/Sources/ResoucesCode/Image.swift
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Home/Meal/MealMenuView.swift
Labels: chore
