Repository team-xquare/xquare-iOS, pull requests merged in 2022-07, with the labels that each got.

#70 🔀 :: (#69) Realm 흔적 삭제
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
Labels: chore

#75 🔀 :: (#74) 세미콜론디자인 라이브러리 버전 업데이트
  Tuist/Dependencies.swift
Labels: chore

#68 🔀 :: (#67) tab view setting
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Application/XQUAREApp.swift
  Application/Sources/Scene/Application/ApplicationView.swift
  Application/Sources/Scene/Entire/EntireView.swift
  Application/Sources/Scene/Feed/FeedView.swift
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Main/MainView.swift
  Application/Sources/Scene/Schedule/ScheduleView.swift
Labels: 기능 추가

#77 🔀 :: (#76) 홈화면 퍼블리싱
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Home/HomeViewModel.swift
  Application/Sources/Scene/Home/MealListCell.swift
  Application/Sources/Scene/Home/MealMenuView.swift
  Application/Sources/Scene/Home/PointsView.swift
Labels: 기능 추가

#84 🔀 :: (#73) AuthService to PureDI
  Services/AuthService/Sources/DI/AuthServiceAssembly.swift
  Services/AuthService/Sources/DI/AuthServiceDependency.swift
Labels: 리팩토링

#85 🔀 :: (#82) remove swinject
  Application/Sources/Application/XQUAREApp.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
Labels: 프로젝트 설정

#87 🔀 :: (#86) SQLiteModule private -> public
  Modules/SQLiteModule/Sources/SQLiteTask.swift
Labels: chore

#92 🔀 :: (#91) XQuareApi 프로퍼티 접근제한 public으로 변경
  Modules/RestApiModule/Sources/XquareAPI.swift
  Modules/RestApiModule/Tests/RestApiRemoteDataSourceSpec.swift
Labels: chore

#90 🔀 :: (#88) Delete ApplicationSceneManifest
  Application/SupportingFiles/Info.plist
Labels: 프로젝트 설정

#93 🔀 :: (#89) Application Icon 세팅
  Application/Resources/Assets.xcassets/AppIcon.appiconset/1024x1024 iOS-100.jpg
  Application/Resources/Assets.xcassets/AppIcon.appiconset/120x120 iOS_1-1.jpg
  Application/Resources/Assets.xcassets/AppIcon.appiconset/120x120 iOS_1.jpg
  Application/Resources/Assets.xcassets/AppIcon.appiconset/152x152 iOS.jpg
  Application/Resources/Assets.xcassets/AppIcon.appiconset/167x167 iOS.jpg
  Application/Resources/Assets.xcassets/AppIcon.appiconset/180x180 iOS_1.jpg
  Application/Resources/Assets.xcassets/AppIcon.appiconset/20x20 iOS.jpg
  Application/Resources/Assets.xcassets/AppIcon.appiconset/29x29 iOS.jpg
  Application/Resources/Assets.xcassets/AppIcon.appiconset/40x40 iOS-1.jpg
  Application/Resources/Assets.xcassets/AppIcon.appiconset/40x40 iOS-2.jpg
  Application/Resources/Assets.xcassets/AppIcon.appiconset/40x40 iOS.jpg
  Application/Resources/Assets.xcassets/AppIcon.appiconset/58x58 iOS_1 (1).jpg
  Application/Resources/Assets.xcassets/AppIcon.appiconset/58x58 iOS_1.jpg
  Application/Resources/Assets.xcassets/AppIcon.appiconset/60x60 iOS.jpg
  Application/Resources/Assets.xcassets/AppIcon.appiconset/76x76 iOS 2.jpg
  Application/Resources/Assets.xcassets/AppIcon.appiconset/80x80 iOS_1-1.jpg
  Application/Resources/Assets.xcassets/AppIcon.appiconset/80x80 iOS_1.jpg
  Application/Resources/Assets.xcassets/AppIcon.appiconset/87x87 iOS.jpg
  Application/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: 프로젝트 설정

#95 🔀 :: (#94) RestApiRemoteDataSource 접근제한 변경
  Modules/RestApiModule/Sources/RestApiRemoteDataSource.swift
Labels: chore

#97 🔀 :: (#96) RestApiRemoteDataSource 접근제한 변경
  Modules/RestApiModule/Sources/RestApiRemoteDataSource.swift
Labels: chore

#99 🔀 :: (#96) RestApiRemoteDataSource init 접근제한 변경
  Modules/RestApiModule/Sources/RestApiRemoteDataSource.swift
Labels: chore

#107 🔀 :: (#104) LaunchScreen
  Application/Resources/Assets.xcassets/Image/Contents.json
  Application/Resources/Assets.xcassets/Image/Logo.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Logo.imageset/New logo@4x 1.png
  Application/Resources/Assets.xcassets/Image/Logo.imageset/New logo@4x 2.png
  Application/Resources/Assets.xcassets/Image/Logo.imageset/New logo@4x 3.png
  Application/Resources/LaunchScreen.storyboard
  Application/Sources/ResoucesCode/Image.swift
Labels: 기능 추가

#108 🔀 :: (#100) bundle display name 수정
  Application/SupportingFiles/Info.plist
Labels: 프로젝트 설정

#109 🔀 :: (#101) RestApiModule PureDI
  Modules/RestApiModule/Sources/DI/RestApiModuleDependcy.swift
Labels: chore

#110 🔀 :: (#51) Testflight
  .github/secrets/Certificates.p12.gpg
  .github/secrets/ExportOptions.plist
  .github/secrets/XQUARE_GithubActions.mobileprovision.gpg
  .github/workflows/Testflight.yml
  Application/SupportingFiles/Info.plist
  Tuist/ProjectDescriptionHelpers/Project Frame/Project+DynamicFramework.swift
  Tuist/ProjectDescriptionHelpers/RemoveStaticFrameworksScripts.swift
Labels: 프로젝트 설정

#112 🔀 :: (#111) RestApiModuleDependency 접근제한 변경
  .github/workflows/Testflight.yml
  Modules/RestApiModule/Sources/DI/RestApiModuleDependcy.swift
Labels: chore

#81 🔀 :: ( #78) MealDataService
  Services/MealDataService/Project.swift
  Services/MealDataService/Sources/DI/MealDataServiceDependency.swift
  Services/MealDataService/Sources/Data/Remote/API/MealAPI.swift
  Services/MealDataService/Sources/Data/Remote/DateSource/RemoteMealDataSource.swift
  Services/MealDataService/Sources/Data/Remote/DateSource/RemoteMealDataSourceImpl.swift
  Services/MealDataService/Sources/Data/Remote/Request/MonthToMealMenuRequest.swift
  Services/MealDataService/Sources/Data/Remote/Response/DayToMealMenuResponse.swift
  Services/MealDataService/Sources/Data/Remote/Response/MonthToMealMenuListResponse.swift
  Services/MealDataService/Sources/Data/Remote/Response/MonthToMealMenuResponse.swift
  Services/MealDataService/Sources/Data/Repository/MealRepositoryImpl.swift
  Services/MealDataService/Sources/Domain/Entity/DayToMealMenuEntity.swift
  Services/MealDataService/Sources/Domain/Entity/MonthToMealMenuEntity.swift
  Services/MealDataService/Sources/Domain/Entity/MonthToMealMenuRequestEntity.swift
  Services/MealDataService/Sources/Domain/Error/MealServiceError.swift
  Services/MealDataService/Sources/Domain/Repository/MealRepository.swift
  Services/MealDataService/Sources/Domain/UseCase/FetchDayToMealMenuUseCase.swift
  Services/MealDataService/Sources/Domain/UseCase/FetchMonthToMealMenuUseCase.swift
  Services/MealDataService/Sources/Util/Date + String.swift
  Services/MealDataService/Tests/MealDataServiceSpec.swift
Labels: 기능 추가

#114 🔀 :: (#113) RestApiModuleDependency 삭제
  Modules/RestApiModule/Sources/DI/RestApiModuleDependcy.swift
Labels: chore

#117 🔀 :: (#116) SQLiteModule 삭제
  Modules/SQLiteModule/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Modules.swift
Labels: chore

#120 🔀 :: (#119) Date Util Module
  Modules/DateUtilModule/Project.swift
  Modules/DateUtilModule/Sources/DateFormat.swift
  Modules/DateUtilModule/Sources/DateToString.swift
  Modules/DateUtilModule/Sources/StringToDate.swift
  Modules/DateUtilModule/Tests/DateToStringSpec.swift
  Modules/DateUtilModule/Tests/StringToDateSpec.swift
Labels: 기능 추가

#122 🔀 :: (#121) AuthService DataUtilModule 대응
  Services/AuthService/Project.swift
  Services/AuthService/Sources/Data/Local/DataSource/LoaclTokenDataSourceImpl.swift
  Services/AuthService/Sources/Data/Util/DateUtil.swift
Labels: chore

#124 🔀 :: (#123) internal init -> public init
  Modules/RxOfflineCacheModule/Sources/OfflineCacheUtil.swift
Labels: chore

#118 🔀 :: (#115) MealDataService Local
  Services/MealDataService/Project.swift
  Services/MealDataService/Sources/DI/MealDataServiceDependency.swift
  Services/MealDataService/Sources/Data/Local/DataSource/LocalDataSource.swift
  Services/MealDataService/Sources/Data/Local/DataSource/LocalDataSourceImpl.swift
  Services/MealDataService/Sources/Data/Local/Entity/MealMenu.swift
  Services/MealDataService/Sources/Data/Local/MealDataServiceSQLiteTask.swift
  Services/MealDataService/Sources/Data/Repository/MealRepositoryImpl.swift
  Services/MealDataService/Sources/Domain/Entity/MonthToMealMenuRequestEntity.swift
  Services/MealDataService/Sources/Domain/UseCase/FetchDayToMealMenuUseCase.swift
  Services/MealDataService/Sources/Util/Date + String.swift
Labels: 기능 추가

#131 🔀 :: (#130) SD; 버전 업데이트 `1.2.1`
  Tuist/Dependencies.swift
Labels: chore

#133 🔀 :: (#132) SD; 버전 업데이트 `1.2.2`
  Tuist/Dependencies.swift
Labels: chore

#137 🔀 :: (#136) SD; 버전 업데이트
  Tuist/Dependencies.swift
Labels: chore

#127 🔀 :: (#126) 홈화면 UI 코드 리펙토링
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Home/HomeViewModel.swift
  Application/Sources/Scene/Home/Meal/MealListCell.swift
  Application/Sources/Scene/Home/Meal/MealMenuView.swift
  Application/Sources/Scene/Home/MealMenuView.swift
  Application/Sources/Scene/Home/PointsView.swift
  Application/Sources/Scene/Home/Profile/ProfileView.swift
  Application/Sources/Scene/Main/MainView.swift
Labels: 리팩토링

#141 🔀 :: (#140) MealMenuEntity 접근제한 public으로 변경
  Services/MealDataService/Sources/Domain/Entity/DayToMealMenuEntity.swift
  Services/MealDataService/Sources/Domain/Entity/MonthToMealMenuEntity.swift
Labels: chore

#143 🔀 :: (#142) MealDataService UseCase 접근제한 public으로 변경하기
  Services/MealDataService/Sources/Domain/UseCase/FetchDayToMealMenuUseCase.swift
  Services/MealDataService/Sources/Domain/UseCase/FetchMonthToMealMenuUseCase.swift
Labels: chore

#145 🔀 :: (#144) SD; 1.5.0 업데이트 및 대응
  Application/Sources/Scene/Home/Meal/MealListCell.swift
  Application/Sources/Scene/Home/Meal/MealMenuView.swift
  Application/Sources/Scene/Home/Profile/ProfileView.swift
  Application/Sources/Scene/Main/MainView.swift
  Tuist/Dependencies.swift
Labels: chore

#148 🔀 :: (#147) 라이트 모드 고정
  Application/SupportingFiles/Info.plist
Labels: chore

#146 🔀 :: (#138) TabView AccentColor 지정
  Application/Sources/Scene/Main/MainView.swift
Labels: chore

#150 🔀 :: (#149) MealDataService 접근제한 변경하기
  Services/MealDataService/Sources/Domain/Entity/MonthToMealMenuRequestEntity.swift
Labels: chore

#152 🔀 :: (#151) MealDataService RequestEntity 이니셜라이저 접근제한 변경
  Services/MealDataService/Sources/Domain/Entity/MonthToMealMenuRequestEntity.swift
Labels: chore

#158 🔀 :: (#156) setting XWebView
  Application/Project.swift
  Modules/XWebKit/Project.swift
  Modules/XWebKit/Sources/.gitkeep
  Modules/XWebKit/Tests/.gitkeep
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Modules.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
Labels: 프로젝트 설정

#159 🔀 :: (#157) SQLiteModule 디렉터리 삭제
  Modules/SQLiteModule/Sources/.gitkeep
  Modules/SQLiteModule/Sources/SQLiteError.swift
  Modules/SQLiteModule/Sources/SQLiteTask.swift
  Modules/SQLiteModule/Sources/xquare.sqlite
  Modules/SQLiteModule/Tests/SQLiteTaskSpec.swift
Labels: chore

#160 🔀 :: (#154) MealDataService Entity 네이밍 변경 및 구조 변경
  Services/MealDataService/Sources/DI/MealDataServiceDependency.swift
  Services/MealDataService/Sources/Data/Local/DataSource/LocalDataSource.swift
  Services/MealDataService/Sources/Data/Local/DataSource/LocalDataSourceImpl.swift
  Services/MealDataService/Sources/Data/Local/MealDataServiceSQLiteTask.swift
  Services/MealDataService/Sources/Data/Remote/API/MealAPI.swift
  Services/MealDataService/Sources/Data/Remote/DateSource/RemoteMealDataSource.swift
  Services/MealDataService/Sources/Data/Remote/DateSource/RemoteMealDataSourceImpl.swift
  Services/MealDataService/Sources/Data/Remote/Response/DayToMealMenuResponse.swift
  Services/MealDataService/Sources/Data/Remote/Response/MealMenuPerDayResponse.swift
  Services/MealDataService/Sources/Data/Remote/Response/MealMenuPerMonthListResponse.swift
  Services/MealDataService/Sources/Data/Remote/Response/MealMenuPerMonthResponse.swift
  Services/MealDataService/Sources/Data/Remote/Response/MonthToMealMenuListResponse.swift
  Services/MealDataService/Sources/Data/Remote/Response/MonthToMealMenuResponse.swift
  Services/MealDataService/Sources/Data/Repository/MealRepositoryImpl.swift
  Services/MealDataService/Sources/Domain/Entity/DayToMealMenuEntity.swift
  Services/MealDataService/Sources/Domain/Entity/MealMenuEntity.swift
  Services/MealDataService/Sources/Domain/Entity/MonthToMealMenuEntity.swift
  Services/MealDataService/Sources/Domain/Entity/MonthToMealMenuRequestEntity.swift
  Services/MealDataService/Sources/Domain/Enum/MealTime.swift
  Services/MealDataService/Sources/Domain/Repository/MealRepository.swift
  Services/MealDataService/Sources/Domain/UseCase/FetchDayToMealMenuUseCase.swift
  Services/MealDataService/Sources/Domain/UseCase/FetchMealMenuPerDayUseCase.swift
  Services/MealDataService/Sources/Domain/UseCase/FetchMealMenuPerMonthUseCase.swift
  Services/MealDataService/Sources/Domain/UseCase/FetchMonthToMealMenuUseCase.swift
Labels: chore

#163 🔀 :: (#162) MealDataService MealTime + mealTimeOrder
  Services/MealDataService/Sources/Domain/Enum/MealTime.swift
Labels: 기능 추가

#166 🔀 :: (#165) MealMenuEntity 추가 및 변경
  Services/MealDataService/Sources/Data/Local/DataSource/LocalDataSource.swift
  Services/MealDataService/Sources/Data/Local/DataSource/LocalDataSourceImpl.swift
  Services/MealDataService/Sources/Data/Local/MealDataServiceSQLiteTask.swift
  Services/MealDataService/Sources/Data/Remote/DateSource/RemoteMealDataSource.swift
  Services/MealDataService/Sources/Data/Remote/DateSource/RemoteMealDataSourceImpl.swift
  Services/MealDataService/Sources/Data/Remote/Response/MealMenuPerDayResponse.swift
  Services/MealDataService/Sources/Data/Remote/Response/MealMenuPerMonthListResponse.swift
  Services/MealDataService/Sources/Data/Remote/Response/MealMenuPerMonthResponse.swift
  Services/MealDataService/Sources/Data/Repository/MealRepositoryImpl.swift
  Services/MealDataService/Sources/Domain/Entity/MealMenuEntity.swift
  Services/MealDataService/Sources/Domain/Entity/MealMenuPerDayEntity.swift
  Services/MealDataService/Sources/Domain/Repository/MealRepository.swift
  Services/MealDataService/Sources/Domain/UseCase/FetchMealMenuPerDayUseCase.swift
  Services/MealDataService/Sources/Domain/UseCase/FetchMealMenuPerMonthUseCase.swift
Labels: chore

#168 🔀 :: (#167) Update SD; to 1.6.0
  Tuist/Dependencies.swift
Labels: chore
