Repository team-xquare/xquare-iOS, pull requests merged in 2022-12, with the labels that each got.

#324 🔀 :: (#322) 모듈 이름 변경 및 로직 변경
  Modules/RxOfflineCacheModule/Sources/OfflineCacheUtil.swift
  Modules/RxOfflineCacheModule/Tests/OfflineCacheUtilSpec.swift
  Modules/XOfflineCache/Project.swift
  Modules/XOfflineCache/Sources/OfflineCacheUtil.swift
  Modules/XOfflineCache/Tests/OfflineCacheUtilSpec.swift
  Services/MealDataService/Project.swift
  Services/MealDataService/Sources/Data/Repository/MealRepositoryImpl.swift
  Services/UserService/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Modules.swift
Labels: 리팩토링, 기능 추가, 프로젝트 설정

#355 🔀 :: (#354) PNG이미지를 SVG이미지로 전환합니다.
  Application/Resources/Assets.xcassets/Image/Icon/Application.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/Application.imageset/application.svg
  Application/Resources/Assets.xcassets/Image/Icon/Application.imageset/application1x.png
  Application/Resources/Assets.xcassets/Image/Icon/BackButton.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/BackButton.imageset/backbutton.svg
  Application/Resources/Assets.xcassets/Image/Icon/BackButton.imageset/백버튼.png
  Application/Resources/Assets.xcassets/Image/Icon/Bell.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/Bell.imageset/bell.svg
  Application/Resources/Assets.xcassets/Image/Icon/Bell.imageset/bell1x.png
  Application/Resources/Assets.xcassets/Image/Icon/Calendar.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/Calendar.imageset/calander.svg
  Application/Resources/Assets.xcassets/Image/Icon/Calendar.imageset/calendar1x.png
  Application/Resources/Assets.xcassets/Image/Icon/Entire.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/Entire.imageset/entire.svg
  Application/Resources/Assets.xcassets/Image/Icon/Entire.imageset/entire1x.png
  Application/Resources/Assets.xcassets/Image/Icon/Feed.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/Feed.imageset/feed.svg
  Application/Resources/Assets.xcassets/Image/Icon/Feed.imageset/feed1x.png
  Application/Resources/Assets.xcassets/Image/Icon/Home.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/Home.imageset/home.svg
  Application/Resources/Assets.xcassets/Image/Icon/Home.imageset/home1x.png
  Application/Resources/Assets.xcassets/Image/Icon/Setting.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/Setting.imageset/setting.png
  Application/Resources/Assets.xcassets/Image/Icon/Setting.imageset/setting.svg
  Application/Resources/Assets.xcassets/Image/Icon/ThumbUp.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/ThumbUp.imageset/thumb-up.png
  Application/Resources/Assets.xcassets/Image/Icon/ThumbUp.imageset/thumbsup.svg
  Application/Resources/Assets.xcassets/Image/Icon/User.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/User.imageset/user.png
  Application/Resources/Assets.xcassets/Image/Icon/User.imageset/user.svg
  Application/Resources/Assets.xcassets/Image/Icon/ViewMore.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/ViewMore.imageset/ViewMore.png
  Application/Resources/Assets.xcassets/Image/Icon/ViewMore.imageset/viewmore.svg
  Application/Resources/Assets.xcassets/Image/Icon/WarningTriangle.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/WarningTriangle.imageset/warning-triangle.png
  Application/Resources/Assets.xcassets/Image/Icon/WarningTriangle.imageset/warningtriangle.svg
  Application/Resources/Assets.xcassets/Image/Icon/bell.badge.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/bell.badge.imageset/bell.badge.svg
  Application/Resources/Assets.xcassets/Image/Icon/bell.badge.imageset/bell.badge1x.png
  Application/Resources/Assets.xcassets/Image/Logo.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Logo.imageset/New logo@4x 1.png
  Application/Resources/Assets.xcassets/Image/Logo.imageset/logo.svg
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-DDYZD.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-DDYZD.imageset/DDYZD1x.png
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-DDYZD.imageset/ddyzd.svg
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-DMS.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-DMS.imageset/DMS1x.png
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-DMS.imageset/dms@4x 1.svg
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-DNMS.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-DNMS.imageset/DNMS1x.png
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-DNMS.imageset/dnms.svg
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-Jobits.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-Jobits.imageset/JOBITS1x.png
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-Jobits.imageset/jobies.svg
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-Xquare.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-Xquare.imageset/XQUARE1x.png
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-Xquare.imageset/xquare.svg
  Application/Sources/Modifier/Navigation/NavigationBackButton.swift
  Application/Sources/Scene/MealDetail/MealDetailView.swift
  Application/Sources/Scene/PointHistory/PointHistoryView.swift
Labels: chore

#356 🔀 :: (#345) MealDataService LocalDB 연동
  Application/Sources/Scene/MealDetail/Cell/MealDetailCell.swift
  Services/MealDataService/Project.swift
  Services/MealDataService/Sources/Data/Local/DataSource/LocalDataSource.swift
  Services/MealDataService/Sources/Data/Local/DataSource/LocalDataSourceImpl.swift
  Services/MealDataService/Sources/Data/Local/Entity/MealMenu.swift
  Services/MealDataService/Sources/Data/Local/MealDataServiceSQLiteTask.swift
  Services/MealDataService/Sources/Data/Repository/MealRepositoryImpl.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
Labels: 기능 추가

#365 🔀 :: (#362) XWebKit 데모앱 추가
  DemoApps/XWebKitDemoApp/Project.swift
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-114.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-120 1.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-128.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-136.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-152.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-167.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-192.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-58.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-60.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-80.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-87.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/Contents.json
  DemoApps/XWebKitDemoApp/Resources/LaunchScreen.storyboard
  DemoApps/XWebKitDemoApp/Sources/XQUAREApp.swift
  DemoApps/XWebKitDemoApp/Sources/XWebKitTester.swift
  DemoApps/XWebKitDemoApp/SupportingFiles/Info.plist
  Workspace.swift
Labels: 프로젝트 설정

#366 🔀 :: (#341) XWebKit에 photo picker 브릿지 추가
  Modules/XWebKit/Project.swift
  Modules/XWebKit/Sources/ComposedWebView/ComposedWebView.swift
  Modules/XWebKit/Sources/ComposedWebView/WebViewCoordinator.swift
  Modules/XWebKit/Sources/XWebKitState.swift
  Modules/XWebKit/Sources/XWebKitView.swift
Labels: 기능 추가

#371 🔀 :: (#364) 마이페이지 뷰모델 작성
  Application/Resources/Assets.xcassets/Image/DefaultImage.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/DefaultImage.imageset/defaultImage.svg
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Home/Profile/ProfileView.swift
  Application/Sources/Scene/MealDetail/MealDetailViewModel.swift
  Application/Sources/Scene/MyPage/MyPageView.swift
  Application/Sources/Scene/MyPage/MyPageViewModel.swift
  Application/Sources/Scene/MyPage/ProfileImage/ProfileImageView.swift
  Services/AttachmentService/Sources/DI/AttachmentServiceDependency.swift
  Services/AttachmentService/Sources/Data/Remote/API/AttachmentAPI.swift
  Services/AttachmentService/Sources/Data/Remote/Response/ImageUrlResponse.swift
  Services/UserService/Sources/DI/UserServiceDependency.swift
  Services/UserService/Sources/Data/Remote/API/UserAPI.swift
  Services/UserService/Sources/Data/Remote/DataSource/RemotaUserDataSource.swift
  Services/UserService/Sources/Data/Remote/DataSource/RemoteUserDataSourceImpl.swift
  Services/UserService/Sources/Data/Remote/Repository/UserRepositoryImpl.swift
  Services/UserService/Sources/Data/Remote/Response/ProfileResponse.swift
  Services/UserService/Sources/Domain/Entity/ProfileEntity.swift
  Services/UserService/Sources/Domain/Repository/UserRepository.swift
  Services/UserService/Sources/Domain/UseCase/EditProfileImageUseCase.swift
  Services/UserService/Sources/Domain/UseCase/FetchProfileUseCase.swift
  Tuist/Dependencies.swift
Labels: 기능 추가

#373 🔀 :: (#372) SwipeBack
  Application/Sources/Extension/UINavigationController.swift
Labels: chore

#375 🔀 :: (#351) FaceID를 통한 자동 로그인
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/Login/LoginView.swift
  Application/Sources/Scene/Login/LoginViewModel.swift
  Application/SupportingFiles/Info.plist
  Services/AuthService/Sources/DI/AuthServiceDependency.swift
  Services/AuthService/Sources/Data/Local/DataSource/LocalAuthDataSource.swift
  Services/AuthService/Sources/Data/Local/DataSource/LocalAuthDataSourceImpl.swift
  Services/AuthService/Sources/Data/Repository/AuthRepositoryImpl.swift
  Services/AuthService/Sources/Domain/Entity/IdAndPasswordEntity.swift
  Services/AuthService/Sources/Domain/Repository/AuthRepository.swift
  Services/AuthService/Sources/Domain/UseCase/AutoLoginUseCase.swift
Labels: 기능 추가
