Repository team-xquare/xquare-iOS, pull requests merged in 2022-10, with the labels that each got.

#286 🔀 :: (#285) 유저서비스 에러 및 수정
  Services/UserService/Project.swift
  Services/UserService/Sources/Data/Remote/API/UserAPI.swift
  Services/UserService/Sources/Data/Remote/DataSource/RemotaUserDataSource.swift
  Services/UserService/Sources/Data/Remote/DataSource/RemoteUserDataSourceImpl.swift
  Services/UserService/Sources/Data/Remote/Repository/UserRepositoryImpl.swift
  Services/UserService/Sources/Data/Remote/Response/UserResponse.swift
  Services/UserService/Sources/Domain/Repository/UserRepository.swift
  Services/UserService/Sources/Domain/UseCase/FetchUserPointUseCase.swift
Labels: chore, 기능 추가

#280 🔀 :: (#279) RestApiModule 관련 의존성 정리
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/Home/HomeView.swift
  Modules/RestApiModule/Sources/RestApiRemoteDataSource.swift
  Services/MealDataService/Project.swift
  Services/MealDataService/Sources/DI/MealDataServiceDependency.swift
  Services/UserService/Sources/DI/UserServiceDependency.swift
Labels: 리팩토링

#277 🔀 :: (#234) DEV scheme에서 시스템로그 비활성화
  Application/Project.swift
Labels: 프로젝트 설정

#278 🔀 :: (#215) KeychainModule 주석 수정
  Modules/KeychainModule/Sources/KeychainModule.swift
Labels: chore

#292 🔀 :: (#291) 필요없는 테스트 파일들 삭제
  Modules/KeychainModule/Tests/.gitkeep
  Modules/RestApiModule/Tests/.gitkeep
  Modules/RestApiModule/Tests/RestApiRemoteDataSourceSpec.swift
  Modules/XEnvironment/Tests/.gitkeep
  Modules/XNavigationAndTab/Tests/.gitkeep
  Modules/XWebKit/Tests/.gitkeep
  Services/AuthService/Tests/.gitkeep
  Services/MealDataService/Tests/.gitkeep
  Services/MealDataService/Tests/MealDataServiceSpec.swift
  Services/UserService/Tests/.gitkeep
Labels: 프로젝트 설정

#304 🔀 :: (#302, #303) 프로젝트 구조 개편
  Application/Project.swift
  Application/Resources/Assets.xcassets/Image/Icon/Setting.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/ViewMore.imageset/Contents.json
  Application/Sources/Application/AppDependency.swift
  Modules/KeychainModule/Project.swift
  Modules/RestApiModule/Project.swift
  Modules/RestApiModule/Sources/RestApiRemoteDataSource.swift
  Modules/RxOfflineCacheModule/Project.swift
  Modules/XDateUtil/Project.swift
  Modules/XEnvironment/Project.swift
  Modules/XNavigationAndTab/Project.swift
  Modules/XWebKit/Project.swift
  Services/AuthService/Project.swift
  Services/AuthService/Sources/DI/AuthServiceDependency.swift
  Services/MealDataService/Project.swift
  Services/MealDataService/Sources/DI/MealDataServiceDependency.swift
  Services/UserService/Project.swift
  Services/UserService/Sources/DI/UserServiceDependency.swift
  Tuist/ProjectDescriptionHelpers/Project Frame/Project+Framework.swift
Labels: 프로젝트 설정

#306 🔀 :: (#301) XWebKit add error bridge
  Modules/XWebKit/Sources/ComposedWebView/ComposedWebView.swift
  Modules/XWebKit/Sources/ComposedWebView/WebViewCoordinator.swift
  Modules/XWebKit/Sources/XWebKitState.swift
  Modules/XWebKit/Sources/XWebKitView.swift
Labels: 기능 추가

#313 🔀 :: (#312) 아이콘 재설정
  Application/Resources/Assets.xcassets/Image/Icon/Setting.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/Setting.imageset/setting.png
  Application/Resources/Assets.xcassets/Image/Icon/Setting.imageset/setting2x.png
  Application/Resources/Assets.xcassets/Image/Icon/Setting.imageset/setting3x.png
  Application/Resources/Assets.xcassets/Image/Icon/ViewMore.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/ViewMore.imageset/ViewMore.png
  Application/Resources/Assets.xcassets/Image/Icon/ViewMore.imageset/ViewMore2x.png
  Application/Resources/Assets.xcassets/Image/Icon/ViewMore.imageset/ViewMore3x.png
  Application/Widget/Resources/Assets.xcassets/AppIcon.appiconset/1024x1024 iOS.jpg
  Application/Widget/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Application/Widget/Resources/Assets.xcassets/AppIcon.appiconset/New logo 최종@4x 1.png
Labels: 버그

#317 🔀 :: (#314) 전체 탭 UI
  Application/Resources/Assets.xcassets/Color/Contents.json
  Application/Resources/Assets.xcassets/Color/EntireTabTopMenuBackground.colorset/Contents.json
  Application/Resources/Assets.xcassets/Color/EntireTabTopMenuText.colorset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/ThumbUp.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/ThumbUp.imageset/thumb-up.png
  Application/Resources/Assets.xcassets/Image/Icon/ThumbUp.imageset/thumb-up2x.png
  Application/Resources/Assets.xcassets/Image/Icon/ThumbUp.imageset/thumb-up3x.png
  Application/Resources/Assets.xcassets/Image/Icon/User.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/User.imageset/user.png
  Application/Resources/Assets.xcassets/Image/Icon/User.imageset/user2x.png
  Application/Resources/Assets.xcassets/Image/Icon/User.imageset/user3x.png
  Application/Resources/Assets.xcassets/Image/Icon/WarningTriangle.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/WarningTriangle.imageset/warning-triangle.png
  Application/Resources/Assets.xcassets/Image/Icon/WarningTriangle.imageset/warning-triangle2x.png
  Application/Resources/Assets.xcassets/Image/Icon/WarningTriangle.imageset/warning-triangle3x.png
  Application/Sources/ResoucesCode/Color.swift
  Application/Sources/ResoucesCode/Image.swift
  Application/Sources/Scene/Entire/EntireView.swift
  Application/Sources/Scene/Entire/ServiceList/ServiceListCellView.swift
  Application/Sources/Scene/Entire/ServiceList/ServiceSectionView.swift
  Application/Sources/Scene/Entire/TopServiceMenu/TopServiceMenuCellView.swift
  Application/Sources/Scene/Entire/TopServiceMenu/TopServiceMenuView.swift
Labels: 기능 추가

#316 🔀 :: (#315) XNavigationAndTab 기능 수정
  Modules/XNavigationAndTab/Sources/BackToMainView.swift
  Modules/XNavigationAndTab/Sources/OnTabSelected.swift
  Modules/XNavigationAndTab/Sources/Util/XNavigationAndTabUtil.swift
  Modules/XNavigationAndTab/Sources/XNavigationAndTabView.swift
Labels: chore, 기능 추가

#321 🔀 :: (#320) fullDateWithTime DateFormat 수정
  Modules/XDateUtil/Sources/DateFormat.swift
Labels: 버그

#330 🔀 :: (#329) XWebKit navigate bridge 변경 대응
  Modules/XWebKit/Sources/ComposedWebView/WebViewCoordinator.swift
  Modules/XWebKit/Sources/XWebKitState.swift
  Modules/XWebKit/Sources/XWebKitView.swift
Labels: chore

#319 🔀 :: (#244) 월별급식메뉴 기능 구현
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/Home/Meal/MealListCell.swift
  Application/Sources/Scene/Home/Meal/MealMenuView.swift
  Application/Sources/Scene/MealDetail/Cell/MealDetailCell.swift
  Application/Sources/Scene/MealDetail/Cell/MealMenuPerMealTimeView.swift
  Application/Sources/Scene/MealDetail/MealDetailView.swift
  Application/Sources/Scene/MealDetail/MealDetailViewModel.swift
  Services/MealDataService/Sources/Data/Local/Entity/MealMenu.swift
  Services/MealDataService/Sources/Data/Local/MealDataServiceSQLiteTask.swift
  Services/MealDataService/Sources/Data/Remote/API/MealAPI.swift
  Services/MealDataService/Sources/Data/Remote/Response/MealMenuPerDayResponse.swift
  Services/MealDataService/Sources/Data/Remote/Response/MealMenuPerMonthResponse.swift
  Services/MealDataService/Sources/Data/Repository/MealRepositoryImpl.swift
  Services/MealDataService/Sources/Domain/Entity/MealMenuEntity.swift
Labels: 기능 추가

#334 🔀 :: (#333) 오늘 급식부터 보여주기
  Application/Sources/Scene/MealDetail/MealDetailView.swift
  Application/Sources/Scene/MealDetail/MealDetailViewModel.swift
Labels: 기능 추가

#336 🔀 :: (#284) 홈 화면 유저 정보 받아오기
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Home/HomeViewModel.swift
  Application/Sources/Scene/Home/Profile/ProfileView.swift
  Application/Sources/Scene/MealDetail/MealDetailView.swift
  Modules/XDateUtil/Sources/DateToString.swift
  Modules/XDateUtil/Sources/StringToDate.swift
  Services/UserService/Sources/DI/UserServiceDependency.swift
  Services/UserService/Sources/Data/Remote/API/UserAPI.swift
  Services/UserService/Sources/Data/Remote/DataSource/RemotaUserDataSource.swift
  Services/UserService/Sources/Data/Remote/DataSource/RemoteUserDataSourceImpl.swift
  Services/UserService/Sources/Data/Remote/Repository/UserRepositoryImpl.swift
  Services/UserService/Sources/Data/Remote/Response/UserSimpleInformationResponse.swift
  Services/UserService/Sources/Domain/Entity/UserSimpleInformation.swift
  Services/UserService/Sources/Domain/Repository/UserRepository.swift
  Services/UserService/Sources/Domain/UseCase/FetchUseSimpleInformationUseCase.swift
Labels: 기능 추가

#337 🔀 :: (#335) XWebKit 토큰에 "Bearer" 추가
  Modules/XWebKit/Sources/ComposedWebView/ComposedWebView.swift
Labels: chore

#339 🔀 :: (#338) 웹뷰 토큰 방식 쿠키로 변경
  Modules/XWebKit/Sources/ComposedWebView/ComposedWebView.swift
Labels: 리팩토링, chore
