Repository team-xquare/xquare-iOS, pull requests merged in 2023-08, with the labels that each got.

#555 🔀 :: (#553) 로그인 Response 수정
  Application/Sources/Scene/Home/HomeViewModel.swift
  Configurations/develop.xcconfig
  Configurations/product.xcconfig
  Configurations/stage.xcconfig
  Services/AuthService/Sources/Data/Remote/Response/SigninAndRefreshTokenResponse.swift
  Services/AuthService/Sources/Data/Repository/AuthRepositoryImpl.swift
Labels: chore

#557 🔀 :: (#556) 웹뷰 url 변경
  Application/Sources/Scene/Application/ApplicationViewModel.swift
  Application/Sources/Scene/Feed/FeedViewModel.swift
Labels: 버그

#563 🔀 :: (#561) 학사일정 로컬처리
  Application/Sources/Scene/Schedule/AcademicSchedule/AcademicScheduleView.swift
  Application/Sources/Scene/Schedule/AcademicSchedule/AcademicScheduleViewModel.swift
  Services/MealDataService/Sources/DI/MealDataServiceDependency.swift
  Services/MealDataService/Sources/Data/Local/DataSource/LocalMealDataSource.swift
  Services/MealDataService/Sources/Data/Local/DataSource/LocalMealDataSourceImpl.swift
  Services/MealDataService/Sources/Data/Repository/MealRepositoryImpl.swift
  Services/ScheduleService/Project.swift
  Services/ScheduleService/Sources/DI/ScheduleServiceDependency.swift
  Services/ScheduleService/Sources/Data/Local/DataSource/LocalScheduleDataSource.swift
  Services/ScheduleService/Sources/Data/Local/DataSource/LocalScheduleDataSourceImpl.swift
  Services/ScheduleService/Sources/Data/Local/Entity/ScheduleForMonth.swift
  Services/ScheduleService/Sources/Data/Remote/Repository/ScheduleRepositoryImpl.swift
  Services/ScheduleService/Sources/Domain/Entity/ScheduleEntity.swift
  Tuist/Dependencies.swift
Labels: 기능 추가
