Repository team-xquare/xquare-iOS, pull requests merged in 2023-03, with the labels that each got.

#396 🔀 :: (#395) PointService
  Application/Project.swift
  Services/PointService/Project.swift
  Services/PointService/Sources/DI/PointServiceDependency.swift
  Services/PointService/Sources/Data/Remote/API/PointAPI.swift
  Services/PointService/Sources/Data/Remote/DataSource/RemotePointDataSource.swift
  Services/PointService/Sources/Data/Remote/DataSource/RemotePointDataSourceImpl.swift
  Services/PointService/Sources/Data/Remote/Repository/PointRepositoryImpl.swift
  Services/PointService/Sources/Data/Remote/Response/PointHistoryResponse.swift
  Services/PointService/Sources/Data/Remote/Response/PointResponse.swift
  Services/PointService/Sources/Domain/Entity/PointEntity.swift
  Services/PointService/Sources/Domain/Entity/PointHistoryEntity.swift
  Services/PointService/Sources/Domain/Error/PointServiceError.swift
  Services/PointService/Sources/Domain/Repository/PointRepository.swift
  Services/PointService/Sources/Domain/UseCase/FetchPointHistoryUseCase.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Services.swift
Labels: 기능 추가

#398 🔀 :: (#387) XPhotos, XWebKit 모듈 삭제
  Application/Project.swift
  Application/Sources/Scene/MyPage/MyPageView.swift
  DemoApps/XWebKitDemoApp/Project.swift
  Modules/XPhotos/Project.swift
  Modules/XPhotos/Sources/XPhotoPicker/View + XPhotoPicker.swift
  Modules/XPhotos/Sources/XPhotoPicker/XPhotoPicker.swift
  Modules/XPhotos/Sources/XPhotoPicker/XPhotoPickerCoordinator.swift
  Modules/XPhotos/Sources/XPhotoPicker/XPhotoPickerModifier.swift
  Modules/XPhotos/Sources/XPhotoViewer/View + XPhotoViewer.swift
  Modules/XPhotos/Sources/XPhotoViewer/XPhotoViewer.swift
  Modules/XWebKit/Project.swift
  Modules/XWebKit/Sources/ComposedWebView/ComposedWebView.swift
  Modules/XWebKit/Sources/ComposedWebView/WebViewCoordinator.swift
  Modules/XWebKit/Sources/RxWebKit/EstimatedProgress.swift
  Modules/XWebKit/Sources/XWebKitProgressViewStyle.swift
  Modules/XWebKit/Sources/XWebKitState.swift
  Modules/XWebKit/Sources/XWebKitView.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Modules.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
Labels: 기능 추가

#399 🔀 :: (#397) 상벌점 api 연동
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/PointHistory/PointHistoryListCellView.swift
  Application/Sources/Scene/PointHistory/PointHistoryView.swift
  Application/Sources/Scene/PointHistory/PointHistoryViewModel.swift
  Services/PointService/Sources/Data/Remote/API/PointAPI.swift
  Services/PointService/Sources/Data/Remote/DataSource/RemotePointDataSource.swift
  Services/PointService/Sources/Data/Remote/DataSource/RemotePointDataSourceImpl.swift
  Services/PointService/Sources/Data/Remote/Repository/PointRepositoryImpl.swift
  Services/PointService/Sources/Domain/Entity/PointEntity.swift
  Services/PointService/Sources/Domain/Enum/PointType.swift
  Services/PointService/Sources/Domain/Repository/PointRepository.swift
  Services/PointService/Sources/Domain/UseCase/FetchPointHistoryUseCase.swift
Labels: 기능 추가

#394 🔀 :: (#393) 스크롤뷰 위치 변경
  Application/Sources/Scene/Schedule/TimeTable/TimeTableView.swift
Labels: chore

#401 🔀 :: (#400) 테스터들 요구사항 들어주기
  Application/Resources/Assets.xcassets/Color/Onboarding/Onboarding-Pick-Color.colorset/Contents.json
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-Jobits.imageset/jobies.svg
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-Pick.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Onboarding/Onboarding-Pick.imageset/pick-100 1.svg
  Application/Sources/ResoucesCode/Color.swift
  Application/Sources/ResoucesCode/Image.swift
  Application/Sources/Scene/MealDetail/Cell/MealDetailCell.swift
  Application/Sources/Scene/MealDetail/MealDetailView.swift
  Application/Sources/Scene/MealDetail/MealDetailViewModel.swift
  Application/Sources/Scene/Onboarding/OnboardingImageViewer.swift
  Application/Sources/Scene/Schedule/TimeTable/PageControl/PageControlView.swift
  Application/Sources/Scene/Schedule/TimeTable/TimeTableView.swift
  Application/Sources/Scene/Schedule/TimeTable/TimeTableViewModel.swift
  Application/Sources/Scene/Signup/SignupView.swift
  Application/Sources/Scene/Signup/SignupViewModel.swift
  Modules/XDateUtil/Sources/DateFormat.swift
  Services/MealDataService/Sources/Data/Local/DataSource/LocalDataSourceImpl.swift
  Services/MealDataService/Sources/Data/Local/Entity/MealMenu.swift
  Services/MealDataService/Sources/Data/Remote/Response/MealMenuPerDayResponse.swift
  Services/MealDataService/Sources/Data/Remote/Response/MealMenuPerMonthResponse.swift
  Services/MealDataService/Sources/Data/Repository/MealRepositoryImpl.swift
  Services/MealDataService/Sources/Domain/Entity/MealMenuPerDayEntity.swift
  Tuist/Dependencies.swift
Labels: chore

#403 🔀 :: (#402) 세미콜론 디자인 버전 업데이트
  Tuist/Dependencies.swift
Labels: chore

#382 🔀 :: (#377) Feed Screen WebView 추가
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/Feed/FeedView.swift
  Application/Sources/Scene/Feed/FeedViewModel.swift
  Tuist/Dependencies.swift
Labels: 기능 추가

#405 🔀 :: (#404) App Crash
  Application/Sources/Scene/BugReport/DropDown/DropDownSelector.swift
  Application/Sources/Scene/Login/LoginView.swift
  Application/Sources/Scene/Schedule/AcademicSchedule/AcademicScheduleView.swift
  Application/Sources/Scene/Schedule/TimeTable/TimeTableView.swift
  Application/Sources/Scene/WriteSchedule/WriteScheduleViewModel.swift
  Application/SupportingFiles/Info.plist
  Tuist/Dependencies.swift
Labels: chore, 기능 추가

#409 🔀 :: (#407) Keyboard로 인해서 TabView가 올라가는 버그 고침
  Modules/XNavigationAndTab/Sources/XNavigationAndTabView.swift
  Tuist/Dependencies.swift
Labels: 버그

#413 🔀 :: (#410) View Bug 고치기
  Application/Sources/Application/AppDelegate.swift
  Application/Sources/Scene/MealDetail/Cell/MealDetailCell.swift
  Tuist/Dependencies.swift
Labels: 버그, 기능 추가

#417 🔀 :: (#414) 일정 삭제 및 수정 기능 구현
  Application/Resources/Assets.xcassets/Image/Icon/More.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/More.imageset/More.svg
  Application/Resources/Assets.xcassets/Image/Icon/Pencil.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/Pencil.imageset/Vector.svg
  Application/Sources/Application/AppDependency.swift
  Application/Sources/ResoucesCode/Image.swift
  Application/Sources/Scene/EditSchedule/EditScheduleView.swift
  Application/Sources/Scene/Schedule/AcademicSchedule/AcademicScheduleView.swift
  Application/Sources/Scene/Schedule/AcademicSchedule/AcademicScheduleViewModel.swift
  Application/Sources/Scene/Schedule/AcademicSchedule/Cell/AcademicScheduleCell.swift
  Application/Sources/Scene/Schedule/ScheduleView.swift
  Services/ScheduleService/Sources/DI/ScheduleServiceDependency.swift
  Services/ScheduleService/Sources/Data/Remote/API/ScheduleAPI.swift
  Services/ScheduleService/Sources/Data/Remote/DataSource/RemoteScheduleDataSource.swift
  Services/ScheduleService/Sources/Data/Remote/DataSource/RemoteScheduleDataSourceImpl.swift
  Services/ScheduleService/Sources/Data/Remote/Repository/ScheduleRepositoryImpl.swift
  Services/ScheduleService/Sources/Domain/Error/ScheduleServiceError.swift
  Services/ScheduleService/Sources/Domain/Repository/ScheduleRepository.swift
  Services/ScheduleService/Sources/Domain/UseCase/DeleteScheduleUseCase.swift
  Services/ScheduleService/Sources/Domain/UseCase/EditScheduleUseCase.swift
Labels: 기능 추가

#419 🔀 :: (#416) 데모앱 삭제
  DemoApps/XWebKitDemoApp/Project.swift
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-114.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-120 1.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-128.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-136.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-152.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-167.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-192.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-58.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-60.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-80.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/AppIcon.appiconset/Icon-87.png
  DemoApps/XWebKitDemoApp/Resources/Assets.xcassets/Contents.json
  DemoApps/XWebKitDemoApp/Resources/LaunchScreen.storyboard
  DemoApps/XWebKitDemoApp/Sources/XQUAREApp.swift
  DemoApps/XWebKitDemoApp/Sources/XWebKitTester.swift
  DemoApps/XWebKitDemoApp/SupportingFiles/Info.plist
  Workspace.swift
Labels: 프로젝트 설정

#420 🔀 :: (#418) XWebKit 업데이트 대응
  Modules/XNavigationAndTab/Sources/XNavigationAndTabView.swift
Labels: 기능 추가

#424 🔀 :: (#423) Widget 다크모드 대응
  Application/Widget/Sources/Meal/XquareMealWidget.swift
  Application/Widget/Sources/Schedule/ScheduleWidgetCell.swift
  Application/Widget/Sources/Schedule/XquareScheduleWidget.swift
Labels: chore, 기능 추가

#432 🔀 :: (#430) NotificationService
  Services/NotificationService/Project.swift
  Services/NotificationService/Sources/DI/NotificationServiceDependency.swift
  Services/NotificationService/Sources/Data/Remote/API/NotificationAPI.swift
  Services/NotificationService/Sources/Data/Remote/DataSource/RemoteNotificationDataSource.swift
  Services/NotificationService/Sources/Data/Remote/DataSource/RemoteNotificationDataSourceImpl.swift
  Services/NotificationService/Sources/Data/Remote/Repository/NotificationRepositoryImpl.swift
  Services/NotificationService/Sources/Data/Remote/Response/CategoryListResponse.swift
  Services/NotificationService/Sources/Data/Remote/Response/CategoryResponse.swift
  Services/NotificationService/Sources/Data/Remote/Response/NotificationListResponse.swift
  Services/NotificationService/Sources/Data/Remote/Response/NotificationResponse.swift
  Services/NotificationService/Sources/Data/Remote/Response/UnreadCountResponse.swift
  Services/NotificationService/Sources/Domain/Entity/CategoryEntity.swift
  Services/NotificationService/Sources/Domain/Entity/NotificationEntity.swift
  Services/NotificationService/Sources/Domain/Error/NotificationServiceError.swift
  Services/NotificationService/Sources/Domain/Repository/NotificationRepository.swift
  Services/NotificationService/Sources/Domain/UseCase/ActiveNotificationCategoryUseCase.swift
  Services/NotificationService/Sources/Domain/UseCase/CheckNotificationUseCase.swift
  Services/NotificationService/Sources/Domain/UseCase/FetchActivatedCategoryListUseCase.swift
  Services/NotificationService/Sources/Domain/UseCase/FetchNotificationCategoryListUseCase.swift
  Services/NotificationService/Sources/Domain/UseCase/FetchPostedNotificationListUseCase.swift
  Services/NotificationService/Sources/Domain/UseCase/FetchUncheckNotificationCountUseCase.swift
  Services/NotificationService/Sources/Domain/UseCase/InactiveNotifcationCategoryUseCase.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Services.swift
Labels: 기능 추가

#429 🔀 :: (#425) NotificationView
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Notification/Cell/NotificationListCell.swift
  Application/Sources/Scene/Notification/NotificationView.swift
Labels: 기능 추가

#434 🔀 :: (#427) PickService
  Services/PickService/Project.swift
  Services/PickService/Sources/DI/PickServiceDependency.swift
  Services/PickService/Sources/Data/Remote/API/PickAPI.swift
  Services/PickService/Sources/Data/Remote/DataSource/RemotePickDataSource.swift
  Services/PickService/Sources/Data/Remote/DataSource/RemotePickDataSourceImpl.swift
  Services/PickService/Sources/Data/Remote/Repostitory/PickRepositoryImpl.swift
  Services/PickService/Sources/Data/Remote/Response/MovedClassResponse.swift
  Services/PickService/Sources/Data/Remote/Response/OutingPassResponse.swift
  Services/PickService/Sources/Data/Remote/Response/OutingReturnTimeResponse.swift
  Services/PickService/Sources/Domain/Entity/MovedClassEntity.swift
  Services/PickService/Sources/Domain/Entity/OutingPassEntity.swift
  Services/PickService/Sources/Domain/Entity/OutingReturnTimeEntity.swift
  Services/PickService/Sources/Domain/Error/PickServiceError.swift
  Services/PickService/Sources/Domain/Repository/PickRepository.swift
  Services/PickService/Sources/Domain/UseCase/DeleteReturnClassUseCase.swift
  Services/PickService/Sources/Domain/UseCase/FetchMovedClassUseCase.swift
  Services/PickService/Sources/Domain/UseCase/FetchOutingPassUseCase.swift
  Services/PickService/Sources/Domain/UseCase/FetchOutingReturnTimeUseCase.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Services.swift
Labels: 기능 추가

#436 🔀 :: (#435) SDErrorAlert -> SDOkayAlert
  Application/Sources/Scene/Login/LoginView.swift
  Application/Sources/Scene/Schedule/AcademicSchedule/AcademicScheduleView.swift
  Application/Sources/Scene/Signup/SignupView.swift
  Tuist/Dependencies.swift
Labels: chore

#439 🔀 :: (#433) NotificationView ViewModel 연동
  Application/Project.swift
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/MealDetail/Cell/MealMenuPerMealTimeView.swift
  Application/Sources/Scene/Notification/Cell/NotificationListCell.swift
  Application/Sources/Scene/Notification/NotificationView.swift
  Application/Sources/Scene/Notification/NotificationViewModel.swift
  Services/NotificationService/Sources/Data/Remote/API/NotificationAPI.swift
  Services/NotificationService/Sources/Data/Remote/Response/NotificationResponse.swift
  Services/NotificationService/Sources/Domain/Entity/NotificationEntity.swift
  Services/NotificationService/Sources/Domain/Enum/NotificationTopic.swift
  Services/NotificationService/Sources/Domain/UseCase/FetchPostedNotificationListUseCase.swift
Labels: 기능 추가

#437 🔀 :: (#428) PickView publishing
  Application/Project.swift
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Home/HomeViewModel.swift
  Application/Sources/Scene/Home/MovedClass/ClassRoomMoveView.swift
  Application/Sources/Scene/Home/Outing/OutingView.swift
  Application/Sources/Scene/OutingPass/Animation/SlidingTextView.swift
  Application/Sources/Scene/OutingPass/Information/OutingInformationView.swift
  Application/Sources/Scene/OutingPass/OutingPassView.swift
  Application/Sources/Scene/OutingPass/OutingPassViewModel.swift
  Modules/XDateUtil/Sources/StringToDate.swift
  Services/PickService/Sources/DI/PickServiceDependency.swift
  Services/PickService/Sources/Data/Remote/API/PickAPI.swift
  Services/PickService/Sources/Data/Remote/DataSource/RemotePickDataSourceImpl.swift
  Services/PickService/Sources/Data/Remote/Response/OutingPassResponse.swift
  Services/PickService/Sources/Data/Remote/Response/OutingReturnTimeResponse.swift
  Services/PickService/Sources/Domain/Entity/OutingPassEntity.swift
  Services/TimeTableService/Sources/Data/Remote/Response/DayTimeTableResponse.swift
Labels: 기능 추가

#440 🔀 :: (#438) XWebKit update & 웹뷰 토큰 플로우 설계
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/Application/ApplicationView.swift
  Application/Sources/Scene/Application/ApplicationViewModel.swift
  Application/Sources/Scene/Feed/FeedView.swift
  Application/Sources/Scene/Feed/FeedViewModel.swift
  Services/AuthService/Sources/DI/AuthServiceDependency.swift
  Services/AuthService/Sources/Domain/UseCase/RefreshTokenIfExpiredUseCase.swift
  Tuist/Dependencies.swift
Labels: 버그, 리팩토링, 기능 추가

#444 🔀 :: (#443) AcademicSchedule View Bug
  Application/Sources/Scene/Schedule/AcademicSchedule/AcademicScheduleView.swift
Labels: chore
