Repository team-xquare/xquare-iOS, pull requests merged in 2023-04, with the labels that each got.

#442 🔀 :: (#441) MealWidget Bug
  Application/Widget/Sources/Meal/XquareMealWidget.swift
Labels: chore

#448 🔀 :: (#447) TodaySelfStudyTeacher Service
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/OutingPass/OutingPassView.swift
  Application/Sources/Scene/Schedule/TimeTable/Cell/TimeTableCell.swift
  Application/Sources/Scene/Schedule/TimeTable/TimeTableViewModel.swift
  Modules/XNavigationAndTab/Sources/XNavigationAndTabView.swift
  Services/PickService/Sources/DI/PickServiceDependency.swift
  Services/PickService/Sources/Data/Remote/API/PickAPI.swift
  Services/PickService/Sources/Data/Remote/DataSource/RemotePickDataSource.swift
  Services/PickService/Sources/Data/Remote/DataSource/RemotePickDataSourceImpl.swift
  Services/PickService/Sources/Data/Remote/Repostitory/PickRepositoryImpl.swift
  Services/PickService/Sources/Data/Remote/Response/TodaySelfStudyTeacherListResponse.swift
  Services/PickService/Sources/Data/Remote/Response/TodaySelfStudyTeacherResponse.swift
  Services/PickService/Sources/Domain/Entity/TodaySelfStudyTeacherEntity.swift
  Services/PickService/Sources/Domain/Entity/TodaySelfStudyTeacherListEntity.swift
  Services/PickService/Sources/Domain/Repository/PickRepository.swift
  Services/PickService/Sources/Domain/UseCase/FetchTodaySelfStudyTeacherUseCase.swift
  Services/ScheduleService/Sources/Data/Remote/Repository/ScheduleRepositoryImpl.swift
Labels: 기능 추가

#451 🔀 :: (#450) TodaySelfStudyTeacher Publishing
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Scene/Entire/EntireView.swift
  Application/Sources/Scene/Entire/ServiceList/ServiceSectionView.swift
  Application/Sources/Scene/OutingPass/OutingPassView.swift
  Application/Sources/Scene/SelfStudyTeacher/Cell/SelfStudyTeacherCellView.swift
  Application/Sources/Scene/SelfStudyTeacher/SelfStudyTeacherView.swift
  Application/Sources/Scene/SelfStudyTeacher/SelfStudyTeacherViewModel.swift
Labels: 리팩토링, 기능 추가

#452 🔀 :: (#449) Xquare Router를 정리합니다.
  Application/Sources/Application/AppDependency.swift
  Application/Sources/Application/XQUAREApp.swift
  Application/Sources/Modifier/Navigation/NavigationBackButtonWithRouter.swift
  Application/Sources/Router/Route/Route/NavigationNode.swift
  Application/Sources/Router/Route/Route/Router.swift
  Application/Sources/Router/Route/Route/RouterFactory.swift
  Application/Sources/Router/Route/Route/Routing.swift
  Application/Sources/Router/Route/Route/View + Cover.swift
  Application/Sources/Router/XQUARE/XquareRoute.swift
  Application/Sources/Router/XQUARE/XquareRouter.swift
  Application/Sources/Router/XQUARE/XquareRouterFactory.swift
  Application/Sources/Scene/ContentView.swift
  Application/Sources/Scene/Entire/EntireView.swift
  Application/Sources/Scene/Entire/ServiceList/ServiceListCellView.swift
  Application/Sources/Scene/Entire/ServiceList/ServiceSectionView.swift
  Application/Sources/Scene/Entire/TopServiceMenu/TopServiceMenuCellView.swift
  Application/Sources/Scene/Entire/TopServiceMenu/TopServiceMenuView.swift
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Home/Meal/MealMenuView.swift
  Application/Sources/Scene/Home/Outing/OutingView.swift
  Application/Sources/Scene/LaunchScreen/LaunchScreenView.swift
  Application/Sources/Scene/Login/LoginView.swift
  Application/Sources/Scene/Main/MainView.swift
  Application/Sources/Scene/MealDetail/MealDetailView.swift
  Application/Sources/Scene/Notification/NotificationView.swift
  Application/Sources/Scene/Onboarding/OnboardingView.swift
  Application/Sources/Scene/OutingPass/OutingPassView.swift
  Application/Sources/Scene/Schedule/AcademicSchedule/AcademicScheduleView.swift
  Application/Sources/Scene/SelfStudyTeacher/Cell/SelfStudyTeacherCellView.swift
  Application/Sources/Scene/SelfStudyTeacher/SelfStudyTeacherViewModel.swift
  Application/Sources/Scene/Signup/SignupView.swift
  Application/Sources/Scene/WriteSchedule/WriteScheduleView.swift
  Services/PickService/Sources/Domain/UseCase/FetchTodaySelfStudyTeacherUseCase.swift
  Tuist/Dependencies.swift
Labels: 기능 추가

#455 🔀 :: (#454) TodaySelfStudyTeacher Refactoring
  Application/Sources/Scene/SelfStudyTeacher/Cell/SelfStudyTeacherCellView.swift
  Application/Sources/Scene/SelfStudyTeacher/SelfStudyTeacherViewModel.swift
Labels: chore

#456 🔀 :: (#446) Logout
  Application/Sources/Router/Route/Route/Router.swift
  Application/Sources/Router/XQUARE/XquareRoute.swift
  Application/Sources/Router/XQUARE/XquareRouterFactory.swift
  Application/Sources/Scene/Entire/EntireView.swift
  Application/Sources/Scene/Entire/EntireViewModel.swift
  Application/Sources/Scene/Entire/ServiceList/ServiceListCellButtonView.swift
  Application/Sources/Scene/Entire/ServiceList/ServiceSectionButtonView.swift
  Application/Sources/Scene/LaunchScreen/LaunchScreenView.swift
  Application/Sources/Scene/LaunchScreen/LaunchScreenViewModel.swift
  Application/Sources/Scene/Login/LoginView.swift
  Application/Sources/Scene/Login/LoginViewModel.swift
  Application/Sources/Scene/Main/MainView.swift
  Application/Sources/Scene/Onboarding/OnboardingView.swift
  Application/Sources/Scene/Schedule/AcademicSchedule/AcademicScheduleViewModel.swift
  Application/Sources/Scene/Schedule/TimeTable/PageControl/PageControlView.swift
  Application/Sources/Scene/Schedule/TimeTable/TimeTableView.swift
  Application/Sources/Scene/Schedule/TimeTable/TimeTableViewModel.swift
  Application/Sources/Scene/Signup/SignupView.swift
  Services/AuthService/Sources/DI/AuthServiceDependency.swift
  Services/AuthService/Sources/Data/Local/DataSource/LoaclTokenDataSource.swift
  Services/AuthService/Sources/Data/Local/DataSource/LoaclTokenDataSourceImpl.swift
  Services/AuthService/Sources/Data/Repository/AuthRepositoryImpl.swift
  Services/AuthService/Sources/Domain/Repository/AuthRepository.swift
  Services/AuthService/Sources/Domain/UseCase/LogoutUseCase.swift
  Services/NotificationService/Sources/Data/Remote/Repository/NotificationRepositoryImpl.swift
Labels: 기능 추가

#460 🔀 :: (#459) chage id password to faceBook
  Application/Sources/Scene/Login/LoginView.swift
Labels: chore, 기능 추가

#463 🔀 :: (#462) ReleaseBugFix
  Application/Sources/Scene/Entire/EntireView.swift
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Login/LoginView.swift
  Application/Sources/Scene/Main/MainView.swift
  Modules/XDateUtil/Sources/DateToString.swift
  Modules/XDateUtil/Sources/StringToDate.swift
  Modules/XDateUtil/Sources/XDateFormatter.swift
Labels: 버그, chore

#468 🔀 :: (#467) iOS 안드로이드 통합
  Application/Sources/Scene/BugReport/BugReportView.swift
  Application/Sources/Scene/Entire/EntireView.swift
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Home/HomeViewModel.swift
  Application/Sources/Scene/Login/LoginView.swift
  Application/Sources/Scene/Onboarding/OnboardingView.swift
  Application/Sources/Scene/PointHistory/PointHistoryListCellView.swift
  Application/Sources/Scene/PointHistory/PointHistoryView.swift
  Application/Sources/Scene/Schedule/Button/ScheduleButtonView.swift
  Application/Sources/Scene/Schedule/TimeTable/PageControl/PageControlView.swift
  Application/Sources/Scene/Signup/SignupView.swift
  Services/PickService/Sources/Data/Remote/API/PickAPI.swift
  Services/PickService/Sources/Domain/Error/PickServiceError.swift
Labels: 리팩토링, chore

#470 🔀 :: (#469) PickService 주석해제
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Home/HomeViewModel.swift
Labels: chore

#474 🔀 :: (#473) withdrawal
  Application/Sources/Router/XQUARE/XquareRouterFactory.swift
  Application/Sources/Scene/MyPage/MyPageView.swift
  Application/Sources/Scene/MyPage/MyPageViewModel.swift
Labels: 기능 추가
