Repository team-xquare/xquare-iOS, pull requests merged in 2023-09, with the labels that each got.

#560 🔀 :: (#558) 사진 업로드 로직 변경
  Application/Sources/Router/XQUARE/XquareRouterFactory.swift
  Application/Sources/Scene/BugReport/BugReportView.swift
  Application/Sources/Scene/BugReport/BugReportViewModel.swift
  Application/Sources/Scene/MyPage/MyPageView.swift
  Application/Sources/Scene/MyPage/MyPageViewModel.swift
  Services/AttachmentService/Sources/DI/AttachmentServiceDependency.swift
  Services/AttachmentService/Sources/Data/Remote/API/AttachmentAPI.swift
  Services/AttachmentService/Sources/Data/Remote/API/PresignedUrlAPI.swift
  Services/AttachmentService/Sources/Data/Remote/DataSource/RemoteAttachmentDataSource.swift
  Services/AttachmentService/Sources/Data/Remote/DataSource/RemoteAttachmentDataSourceImpl.swift
  Services/AttachmentService/Sources/Data/Remote/Response/ImageUrlResponse.swift
  Services/AttachmentService/Sources/Data/Remote/Response/PresigedUrlResponses.swift
  Services/AttachmentService/Sources/Data/Remote/Response/presigedUrlResponse.swift
  Services/AttachmentService/Sources/Data/Repository/AttachmentRepositoryImpl.swift
  Services/AttachmentService/Sources/Domain/Entity/presigedUrlEntity.swift
  Services/AttachmentService/Sources/Domain/Repository/AttachmentRepository.swift
  Services/AttachmentService/Sources/Domain/UseCase/RequestPresignedUrlUseCase.swift
  Services/AttachmentService/Sources/Domain/UseCase/UploadImageToS3UseCase.swift
Labels: 리팩토링, 기능 추가

#565 🔀 :: (#564) 알림 리스트 버그 수정
  Services/NotificationService/Sources/Data/Remote/Response/NotificationResponse.swift
Labels: 버그

#568 🔀 :: (#567) fix GitHub bugs
  Application/Resources/Assets.xcassets/Image/Icon/Crown.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/Crown.imageset/Crown.svg
  Application/Sources/Scene/GitHubRanking/GithubRankingView.swift
  Application/Sources/Scene/GitHubRanking/GithubRankingViewModel.swift
  Application/Sources/Scene/GitHubRanking/ListCell/RankingListCellView.swift
  Application/Sources/Scene/MyPage/MyPageViewModel.swift
  Tuist/Dependencies.swift
Labels: 버그, chore
