Repository team-xquare/xquare-iOS, pull requests merged in 2023-06, with the labels that each got.

#515 🔀 :: (#514) semicolon design version up
  Application/Sources/Scene/Home/Meal/MealListCell.swift
  Application/Sources/Scene/Notification/Cell/NotificationListCell.swift
  Application/Sources/Scene/PointHistory/PointHistoryListCellView.swift
  Application/Sources/Scene/Schedule/TimeTable/Cell/TimeTableCell.swift
  Application/Sources/Scene/Setting/ToggleCell/ToggleView.swift
  Application/Sources/Scene/Signup/TermsCaptionView.swift
  Application/Widget/Sources/Meal/XquareMealWidget.swift
  Application/Widget/Sources/Schedule/ScheduleWidgetCell.swift
  Application/Widget/Sources/Schedule/XquareScheduleWidget.swift
  Tuist/Dependencies.swift
Labels: chore

#509 🔀 :: (#508) fix release bug
  Application/Resources/Assets.xcassets/Image/Icon/ThumbUp.imageset/Contents.json
  Application/Sources/Scene/ReleaseNote/Cell/ReleaseNoteCellView.swift
Labels: 버그

#512 🔀 :: (#510) notification feed category 추가
  Application/Sources/Scene/Notification/Cell/NotificationListCell.swift
  Services/NotificationService/Sources/Domain/Enum/NotificationTopic.swift
Labels: 리팩토링, chore

#513 🔀 :: (#511) mypage republishing
  Application/Sources/Scene/Entire/EntireView.swift
  Application/Sources/Scene/Entire/ServiceList/ServiceListCellButtonView.swift
  Application/Sources/Scene/Entire/ServiceList/ServiceSectionButtonView.swift
  Application/Sources/Scene/MyPage/Information/MyInfoIDAndBirthDay.swift
  Application/Sources/Scene/MyPage/Information/MyInformationView.swift
  Application/Sources/Scene/MyPage/MyPageView.swift
  Application/Sources/Scene/MyPage/MyPageViewModel.swift
  Application/Sources/Scene/Setting/SettingViewModel.swift
Labels: 리팩토링, chore

#521 🔀 :: (#518) 홈 탭바 누를때마다 급식 포커싱 처리
  Application/Sources/Scene/Home/HomeViewModel.swift
Labels: 버그, 리팩토링, chore

#517 🔀 :: (#516) 하단 바 버튼 햅틱반응
  Modules/XNavigationAndTab/Sources/XNavigationAndTabView.swift
Labels: 기능 추가

#520 🔀 :: (#519) notificationList bug fix
  Application/Sources/Scene/Notification/Cell/NotificationListCell.swift
  Modules/XDateUtil/Sources/DateToString.swift
  Modules/XDateUtil/Sources/monthToDay.swift
  Services/NotificationService/Sources/Data/Remote/Response/NotificationResponse.swift
Labels: 버그, 리팩토링, chore

#527 🔀 :: (#526) 세미콜론 디자인 버전 업
  Tuist/Dependencies.swift
Labels: chore

#525 🔀 :: (#524) 개인 일정 공백버그 수정
  Application/Sources/Scene/WriteSchedule/WriteScheduleViewModel.swift
Labels: 버그

#537 🔀 :: (#536) XWebKit 버전 업
  Tuist/Dependencies.swift
Labels: chore

#533 🔀 :: (#532) ios버전에 따른 위젯 안뜨는 버그 수정
  Application/Project.swift
Labels: 버그

#534 🔀 :: (#531) 캡처 or 녹화했을때 화면 검은색 처리
  Application/Sources/Scene/OutingPass/OutingPassView.swift
Labels: 기능 추가

#545 🔀 :: (#544) ScrollView bottom 패딩주기
  Application/Sources/Scene/MealDetail/MealDetailView.swift
  Application/Sources/Scene/ReleaseNote/ReleaseNoteView.swift
  Application/Sources/Scene/SelfStudyTeacher/SelfStudyTeacherView.swift
Labels: chore
