Repository team-xquare/xquare-iOS, pull requests merged in 2023-05, with the labels that each got.

#477 🔀 :: (#476) 로그아웃 네 아니요 버튼 위치 변경
  Application/Sources/Scene/Entire/EntireView.swift
  Application/Sources/Scene/MyPage/MyPageView.swift
Labels: chore

#479 🔀 :: (#478) SemicolonDesign_iOS 버전 업
  Application/Sources/Scene/EditSchedule/EditScheduleView.swift
  Application/Sources/Scene/Signup/SignupView.swift
  Application/Sources/Scene/WriteSchedule/WriteScheduleView.swift
  Tuist/Dependencies.swift
Labels: 리팩토링, chore

#464 🔀 :: (#461) BugReportService
  Application/Project.swift
  Application/Sources/Router/XQUARE/XquareRouterFactory.swift
  Application/Sources/Scene/BugReport/BugImage/BugImageView.swift
  Application/Sources/Scene/BugReport/BugReportView.swift
  Application/Sources/Scene/BugReport/BugReportViewModel.swift
  Application/Sources/Scene/BugReport/ImportantText/ImportantTextView.swift
  Application/Sources/Scene/SelfStudyTeacher/Cell/SelfStudyTeacherCellView.swift
  Services/BugService/Project.swift
  Services/BugService/Sources/DI/BugServiceDependency.swift
  Services/BugService/Sources/Data/Remote/API/BugAPI.swift
  Services/BugService/Sources/Data/Remote/DataSource/RemoteBugDataSource.swift
  Services/BugService/Sources/Data/Remote/DataSource/RemoteBugDataSourceImpl.swift
  Services/BugService/Sources/Data/Repository/BugRepositoryImpl.swift
  Services/BugService/Sources/Domain/Entity/PostBugReportEntity.swift
  Services/BugService/Sources/Domain/Enum/BugCategory.swift
  Services/BugService/Sources/Domain/Error/BugServiceError.swift
  Services/BugService/Sources/Domain/Repository/BugRepository.swift
  Services/BugService/Sources/Domain/UseCase/PostBugReportUseCase.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Services.swift
Labels: chore, 기능 추가

#488 🔀 :: (#487) fix SwiftLint Bug
  Services/MealDataService/Sources/Data/Local/DataSource/LocalDataSourceImpl.swift
Labels: 버그

#491 🔀 :: (#490) fix notification bug
  Modules/XDateUtil/Sources/DateFormat.swift
  Modules/XDateUtil/Sources/StringToDate.swift
  Services/AuthService/Sources/Data/Local/DataSource/LoaclTokenDataSourceImpl.swift
Labels: 버그

#482 🔀 :: (#481) Change Meal Design
  Application/Sources/Scene/Home/Meal/MealListCell.swift
  Application/Sources/Scene/Home/Meal/MealMenuView.swift
  Application/Sources/Scene/MealDetail/Cell/MealMenuPerMealTimeView.swift
  Services/MealDataService/Sources/Data/Local/DataSource/LocalDataSourceImpl.swift
  Services/MealDataService/Sources/Domain/Enum/MealTime.swift
Labels: chore

#489 🔀 :: (#486) 외출증 폰트 수정 및 외출날짜 추가
  Application/Sources/Scene/OutingPass/Animation/SlidingTextView.swift
  Application/Sources/Scene/OutingPass/Information/OutingInformationView.swift
  Application/Sources/Scene/OutingPass/OutingPassView.swift
  Services/PickService/Sources/Data/Remote/Response/OutingPassResponse.swift
  Services/PickService/Sources/Domain/Entity/OutingPassEntity.swift
Labels: 리팩토링, chore

#485 🔀 :: (#484) release note 구현하기
  Application/Project.swift
  Application/Sources/Router/XQUARE/XquareRoute.swift
  Application/Sources/Router/XQUARE/XquareRouterFactory.swift
  Application/Sources/Scene/BugReport/BugReportViewModel.swift
  Application/Sources/Scene/Entire/EntireView.swift
  Application/Sources/Scene/ReleaseNote/Cell/ReleaseNoteCellView.swift
  Application/Sources/Scene/ReleaseNote/ReleaseNoteView.swift
  Application/Sources/Scene/ReleaseNote/ReleaseViewModel.swift
  Services/BugService/Sources/DI/BugServiceDependency.swift
  Services/BugService/Sources/Data/Remote/API/BugAPI.swift
  Services/ReportService/Project.swift
  Services/ReportService/Sources/DI/ReportServiceDependency.swift
  Services/ReportService/Sources/Data/Remote/API/ReportAPI.swift
  Services/ReportService/Sources/Data/Remote/DataSource/RemoteReportDataSource.swift
  Services/ReportService/Sources/Data/Remote/DataSource/RemoteReportDataSourceImpl.swift
  Services/ReportService/Sources/Data/Remote/Response/ReleaseNoteListResponse.swift
  Services/ReportService/Sources/Data/Remote/Response/ReleaseNoteResponse.swift
  Services/ReportService/Sources/Data/Repository/ReportRepositoryImpl.swift
  Services/ReportService/Sources/Domain/Entity/PostBugReportEntity.swift
  Services/ReportService/Sources/Domain/Entity/ReleaseNoteEntity.swift
  Services/ReportService/Sources/Domain/Entity/ReleaseNoteListEntity.swift
  Services/ReportService/Sources/Domain/Enum/BugCategory.swift
  Services/ReportService/Sources/Domain/Error/ReportServiceError.swift
  Services/ReportService/Sources/Domain/Repository/ReportRepository.swift
  Services/ReportService/Sources/Domain/UseCase/FetchReleaseNoteUseCase.swift
  Services/ReportService/Sources/Domain/UseCase/PostBugReportUseCase.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Services.swift
Labels: 기능 추가

#498 🔀 :: (#495) 시간에 따라 급식 스크롤 포커싱처리
  Application/Sources/Scene/Home/Meal/MealMenuView.swift
Labels: 리팩토링, chore

#501 🔀 :: (#500) fix outing pass bug
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Home/HomeViewModel.swift
  Application/Sources/Scene/OutingPass/OutingPassView.swift
  Services/PickService/Sources/Data/Remote/Response/OutingPassResponse.swift
  Services/PickService/Sources/Domain/Entity/OutingPassEntity.swift
Labels: 버그

#502 🔀 :: (#499) 마이페이지 수정
  Application/Resources/Assets.xcassets/Image/Icon/Camera.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Icon/Camera.imageset/material-symbols_photo-camera-outline.svg
  Application/Sources/ResoucesCode/Image.swift
  Application/Sources/Router/XQUARE/XquareRouterFactory.swift
  Application/Sources/Scene/Entire/EntireView.swift
  Application/Sources/Scene/MyPage/Information/MyInformationView.swift
  Application/Sources/Scene/MyPage/MyPageView.swift
  Application/Sources/Scene/MyPage/MyProfile/MyProfileView.swift
  Application/Sources/Scene/MyPage/MyProfile/ProfileImage/ProfileImageView.swift
Labels: 리팩토링, chore, 기능 추가

#503 🔀 :: (#483) setting page
  Application/Sources/Router/XQUARE/XquareRoute.swift
  Application/Sources/Router/XQUARE/XquareRouterFactory.swift
  Application/Sources/Scene/Home/HomeView.swift
  Application/Sources/Scene/Setting/SettingView.swift
  Application/Sources/Scene/Setting/SettingViewModel.swift
  Application/Sources/Scene/Setting/ToggleCell/ToggleView.swift
  Services/BugService/Sources/Data/Remote/Repository/BugRepositoryImpl.swift
  Services/NotificationService/Sources/DI/NotificationServiceDependency.swift
  Services/NotificationService/Sources/Data/Remote/API/NotificationAPI.swift
  Services/NotificationService/Sources/Data/Remote/DataSource/RemoteNotificationDataSource.swift
  Services/NotificationService/Sources/Data/Remote/DataSource/RemoteNotificationDataSourceImpl.swift
  Services/NotificationService/Sources/Data/Remote/Repository/NotificationRepositoryImpl.swift
  Services/NotificationService/Sources/Data/Remote/Response/CategoryListResponse.swift
  Services/NotificationService/Sources/Data/Remote/Response/CategoryResponse.swift
  Services/NotificationService/Sources/Domain/Entity/CategoryEntity.swift
  Services/NotificationService/Sources/Domain/Enum/NotificationActivateTopic.swift
  Services/NotificationService/Sources/Domain/Repository/NotificationRepository.swift
  Services/NotificationService/Sources/Domain/UseCase/ActiveNotificationCategoryUseCase.swift
  Services/NotificationService/Sources/Domain/UseCase/InactiveNotifcationCategoryUseCase.swift
Labels: 기능 추가

#506 🔀 :: (#505) Local 오타 수정
  Services/AuthService/Sources/DI/AuthServiceDependency.swift
  Services/AuthService/Sources/Data/Local/DataSource/LocalTokenDataSource.swift
  Services/AuthService/Sources/Data/Local/DataSource/LocalTokenDataSourceImpl.swift
  Services/AuthService/Sources/Data/Repository/AuthRepositoryImpl.swift
  Services/AuthService/Sources/Plugin/JWTPulgin.swift
Labels: chore
