Repository team-xquare/xquare-iOS, pull requests merged in 2023-07, with the labels that each got.

#543 🔀 :: (#542) macOS에서 로그인시 iOS기기에 알림이 안오는 버그 수정
  Application/Sources/Application/AppDelegate.swift
  Application/Sources/Scene/Login/LoginViewModel.swift
Labels: 버그

#547 🔀 :: (#546) 급식 깜빡임 버그 수정
  Application/Sources/Scene/Home/HomeViewModel.swift
  Application/Sources/Scene/Home/Meal/MealMenuView.swift
Labels: 버그

#539 🔀 :: (#538) lock screen 구현
  Application/Project.swift
  Application/Widget/Sources/Application/XquareWidget.swift
  Application/Widget/Sources/Meal/XquareMealWidget.swift
  Application/Widget/Sources/TimeTable/TimePeriod.swift
  Application/Widget/Sources/TimeTable/XquareTimeTableWidget.swift
Labels: 기능 추가

#550 🔀 :: (#549) meal lock screen 아침,점심 이미지 변경
  Application/Widget/Sources/Meal/XquareMealWidget.swift
  Application/Widget/Sources/Schedule/XquareScheduleWidget.swift
  Application/Widget/Sources/TimeTable/XquareTimeTableWidget.swift
Labels: chore
